const assert=require('node:assert/strict');
const E=require('../cycle-engine.js');
const now=Date.now(),day=86400,t=Math.floor(now/1000)-60*day;
const bars=Array.from({length:40},(_,i)=>({t:t+i*day,o:100,h:102,l:98,c:100,v:1000}));
const data=b=>({bars:b,quoteTime:Math.floor(now/1000)-10,sessionStart:Math.floor(now/1000)-3600,sessionEnd:Math.floor(now/1000)-100});
assert.equal(E.analyze({},now).code,'WAIT');
assert.equal(E.analyze({bars},now).label,'暂停信号');
assert.equal(E.analyze(data(bars),now,true).code,'WAIT');
const b=bars.concat([{t:t+40*day,o:102,h:105,l:102,c:104,v:1500},{t:t+41*day,o:104,h:105,l:103,c:104,v:1100},{t:t+42*day,o:104,h:105,l:103,c:104.5,v:1100}]);
assert.equal(E.analyze(data(b.slice(0,-2)),now).label,'B2刚触发');
assert.equal(E.analyze(data(b),now).label,'B2已确认（日线结构）');
const broken=b.concat({t:t+43*day,o:104,h:104,l:90,c:91,v:2000});
assert.notEqual(E.analyze(data(broken),now).code,'B2');
const stale={...data(b),quoteTime:Math.floor(now/1000)-1000,sessionEnd:Math.floor(now/1000)+3600};
assert.equal(E.analyze(stale,now).code,'WAIT');
console.log('cycle scenarios passed');
assert.equal(E.watchStatus({label:'观察',stage:'退潮下跌'}),'暂不观察');
assert.equal(E.watchStatus({label:'暂停信号',stage:'趋势延续'}),'数据待核验');
assert.equal(E.watchStatus({label:'B1承接（日线）',stage:'止跌观察'}),'保留观察');
assert.equal(E.watchStatus({label:'观察',stage:'止跌观察'}),'暂不观察');
assert.equal(E.watchStatus({label:'观察',stage:'趋势延续'}),'保留观察');
