const EM='https://push2.eastmoney.com/api/qt/clist/get';
let market='A',onlyStart=false,currentTab='radar';
let state={A:{stocks:[],sectors:[],live:false},HK:{stocks:[],sectors:[],live:false}};
const WATCH_KEY='fundRadarWatchV2',HIST_KEY='fundRadarHistV2';
const demo={A:{sectors:[['光模块',3.8,92],['半导体',2.9,87],['AI服务器',2.4,82],['机器人',1.8,76]],stocks:[['300502','新易盛',6.8,92,18.6,12.4],['300308','中际旭创',5.1,89,16.2,9.4],['002463','沪电股份',4.4,86,12.8,8.1],['300476','胜宏科技',3.9,83,10.2,7.7],['002837','英维克',3.4,79,8.6,6.1],['300394','天孚通信',2.8,76,7.3,5.7]]},HK:{sectors:[['半导体',4.1,91],['互联网',2.7,85],['创新药',2.4,81],['黄金',1.6,73]],stocks:[['00981','中芯国际',5.9,91,42.1,6.8],['01347','华虹半导体',4.7,87,18.4,7.1],['00700','腾讯控股',2.3,82,96.8,1.2],['09988','阿里巴巴-W',2.0,80,74.5,1.6],['06160','百济神州',1.8,76,13.2,1.1],['01024','快手-W',1.5,73,20.8,2.4]]}};
function n(v,d=0){v=Number(v);return Number.isFinite(v)?v:d}
function bn(v){return n(v)/1e8}
function clamp(v,a,b){return Math.max(a,Math.min(b,v))}
function jsonp(url,timeout=7000){return new Promise((resolve,reject)=>{const cb='emcb_'+Date.now()+'_'+Math.random().toString(36).slice(2);const s=document.createElement('script');let done=false;window[cb]=d=>{done=true;clean();resolve(d)};function clean(){delete window[cb];s.remove()}s.onerror=()=>{clean();reject(new Error('network'))};s.src=url+(url.includes('?')?'&':'?')+'cb='+cb+'&_='+Date.now();document.body.appendChild(s);setTimeout(()=>{if(!done){clean();reject(new Error('timeout'))}},timeout)})}
function stockUrl(m){const fs=m==='A'?'m:0+t:6,m:0+t:80,m:1+t:2,m:1+t:23':'m:128+t:3,m:128+t:4,m:128+t:1,m:128+t:2';return `${EM}?pn=1&pz=120&po=1&np=1&fltt=2&invt=2&fid=f6&fs=${encodeURIComponent(fs)}&fields=f12,f14,f2,f3,f5,f6,f8,f10,f62,f184`}
function sectorUrl(m){const fs=m==='A'?'m:90+t:2':'m:128+t:2';return `${EM}?pn=1&pz=40&po=1&np=1&fltt=2&invt=2&fid=f3&fs=${encodeURIComponent(fs)}&fields=f12,f14,f2,f3,f6,f8,f10,f62,f184`}
function scoreStock(x){const pct=clamp(n(x.f3),-10,20),amount=Math.log10(Math.max(1,n(x.f6))),turn=clamp(n(x.f8),0,20),vr=clamp(n(x.f10),0,5),flow=n(x.f184);return clamp(Math.round(45+pct*2.2+(amount-8)*5+turn*.55+vr*2.5+clamp(flow/6,-15,15)),0,99)}
function normalizeStocks(items){return (items||[]).filter(x=>x&&x.f14&&n(x.f2)>0).map(x=>({code:String(x.f12),name:x.f14,price:n(x.f2),pct:n(x.f3),amount:bn(x.f6),turn:n(x.f8),vr:n(x.f10),flow:n(x.f62),flowPct:n(x.f184),score:scoreStock(x)})).sort((a,b)=>b.score-a.score).slice(0,50)}
function normalizeSectors(items){return (items||[]).filter(x=>x&&x.f14).map(x=>({code:String(x.f12||''),name:x.f14,pct:n(x.f3),amount:bn(x.f6),flow:n(x.f62),flowPct:n(x.f184),score:clamp(Math.round(55+n(x.f3)*5+n(x.f184)*.25),0,99)})).sort((a,b)=>b.score-a.score).slice(0,16)}
function fallback(m){return {stocks:demo[m].stocks.map(x=>({code:x[0],name:x[1],pct:x[2],score:x[3],amount:x[4],turn:x[5],vr:1.4,price:0,flowPct:0})),sectors:demo[m].sectors.map(x=>({code:'',name:x[0],pct:x[1],score:x[2],amount:0,flowPct:0}))}}
function getHist(){try{return JSON.parse(localStorage.getItem(HIST_KEY)||'{}')}catch(e){return {}}}
function saveHist(){const h=getHist(),now=Date.now();['A','HK'].forEach(m=>{if(!state[m].live)return;h[m]=h[m]||[];h[m].push({t:now,stocks:Object.fromEntries(state[m].stocks.slice(0,40).map(x=>[x.code,{pct:x.pct,amount:x.amount,score:x.score}])),sectors:Object.fromEntries(state[m].sectors.slice(0,16).map(x=>[x.name,{pct:x.pct,score:x.score,amount:x.amount}]))});h[m]=h[m].filter(x=>now-x.t<45*60*1000).slice(-20)});localStorage.setItem(HIST_KEY,JSON.stringify(h))}
function nearestSnapshot(m,mins){const arr=(getHist()[m]||[]),target=Date.now()-mins*60000;let best=null,dist=Infinity;for(const x of arr){const d=Math.abs(x.t-target);if(d<dist){best=x;dist=d}}return best&&dist<Math.max(4,mins*.55)*60000?best:null}
function accelForStock(x,mins){const s=nearestSnapshot(market,mins);if(!s||!s.stocks[x.code])return null;const p=s.stocks[x.code];return {pct:x.pct-p.pct,score:x.score-p.score,amount:x.amount-p.amount}}
function accelForSector(x,mins){const s=nearestSnapshot(market,mins);if(!s||!s.sectors[x.name])return null;const p=s.sectors[x.name];return {pct:x.pct-p.pct,score:x.score-p.score,amount:x.amount-p.amount}}
function accelScore(x){const a5=accelForStock(x,5),a30=accelForStock(x,30);let v=0;if(a5)v+=a5.score*1.4+a5.pct*7;if(a30)v+=a30.score*.6+a30.pct*3;return clamp(Math.round(v),-99,99)}
async function loadMarket(m){try{const [s,b]=await Promise.all([jsonp(stockUrl(m)),jsonp(sectorUrl(m))]);const stocks=normalizeStocks(s?.data?.diff),sectors=normalizeSectors(b?.data?.diff);if(!stocks.length)throw new Error('empty');state[m]={stocks,sectors,live:true};return true}catch(e){const f=fallback(m);state[m]={...f,live:false};return false}}
function switchMarket(m){market=m;document.getElementById('btnA').classList.toggle('active',m==='A');document.getElementById('btnHK').classList.toggle('active',m==='HK');render()}
function showTab(t){currentTab=t;['radar','flow','night','watch'].forEach(x=>{document.getElementById('panel'+cap(x)).classList.toggle('hide',x!==t);document.getElementById('tab'+cap(x)).classList.toggle('active',x===t);document.getElementById('nav'+cap(x)).classList.toggle('active',x===t)});render()}
function cap(s){return s.charAt(0).toUpperCase()+s.slice(1)}
function toggleOnlyStart(){onlyStart=!onlyStart;document.getElementById('startBtn').textContent=onlyStart?'显示全部':'只看启动';renderStocks()}
function clsPct(v){return v>=0?'up':'down'}
function fmtAmt(v){return v>=100?`${v.toFixed(0)}亿`:v>=1?`${v.toFixed(1)}亿`:`${Math.max(0,v*10000).toFixed(0)}万`}
function accelText(a){if(!a)return '积累中';const v=a.score+a.pct*4;return v>4?'↗ 加速':v<-4?'↘ 减速':'→ 平稳'}
function accelClass(a){if(!a)return 'warn';const v=a.score+a.pct*4;return v>4?'good':v<-4?'hot':'warn'}
function render(){const d=state[market];const top=d.stocks.slice(0,10);const avg=top.reduce((a,x)=>a+x.score,0)/Math.max(1,top.length),ms=Math.round(avg||0);const e=document.getElementById('marketScore');e.textContent=ms||'--';e.className='big score '+(ms>=82?'green':'amber');document.getElementById('marketText').textContent=ms>=86?'资金高度集中：优先强板块前排龙头':ms>=78?'资金活跃：寻找刚放量、仍未高潮的启动股':'资金分散：降低追涨频率，等待集中度提升';const topSector=d.sectors[0];const a5=topSector?accelForSector(topSector,5):null,a30=topSector?accelForSector(topSector,30):null;document.getElementById('m5').textContent=a5?(a5.score>=0?'+':'')+a5.score:'积累中';document.getElementById('m30').textContent=a30?(a30.score>=0?'+':'')+a30.score:'积累中';document.getElementById('focus').textContent=d.sectors.length?Math.round(d.sectors.slice(0,3).reduce((a,x)=>a+x.score,0)/Math.min(3,d.sectors.length)):'--';document.getElementById('liveBadge').textContent=d.live?'公开行情已连接':'演示数据';document.getElementById('liveBadge').className='live '+(d.live?'':'off');document.getElementById('stamp').textContent=`${market==='A'?'A股':'港股'} · ${new Date().toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit'})} 更新`;renderSectors();renderStocks();renderRisks();renderFlow();renderNight();renderWatch()}
function renderSectors(){const d=state[market].sectors;document.getElementById('sectorGrid').innerHTML=d.slice(0,6).map(x=>{const a=accelForSector(x,5);return `<div class="card"><span class="accel">${accelText(a)}</span><strong>${x.name}</strong><div class="${clsPct(x.pct)}" style="font-size:22px;font-weight:800">${x.pct>=0?'+':''}${x.pct.toFixed(2)}%</div><div class="tag ${x.score>=85?'hot':x.score>=76?'good':'warn'}">潮汐 ${x.score}</div><div class="tag ${accelClass(a)}">5m ${a?(a.score>=0?'+':'')+a.score:'--'}</div><div class="flowbar"><i style="width:${clamp(x.score,5,100)}%"></i></div></div>`}).join('')||'<div class="empty">暂无板块数据</div>'}
function label(x){const a=accelScore(x);if(x.score>=88&&a>=0)return['启动',''];if(x.score>=80)return['观察','mid'];return['弱','bad']}
function renderStocks(){let arr=state[market].stocks.map(x=>({...x,acc:accelScore(x)})).sort((a,b)=>(b.score+b.acc*.18)-(a.score+a.acc*.18));if(onlyStart)arr=arr.filter(x=>x.score>=85&&x.acc>=-3);document.getElementById('stockList').innerHTML=arr.slice(0,10).map((x,i)=>{const l=label(x),a=accelForStock(x,5),wat=isWatched(x.code);return `<div class="row tap" onclick="toggleWatch('${x.code}')"><div class="rank">${i+1}</div><div><div class="name">${x.name} <span style="font-size:10px;color:#6f829f">${x.code}</span> <span class="star ${wat?'on':''}">★</span></div><div class="meta">成交 ${fmtAmt(x.amount)} · 换手 ${x.turn.toFixed(1)}% · 量比 ${x.vr.toFixed(1)}</div><div class="badgeLine"><span class="tiny ${x.acc>4?'pos':x.acc<-4?'neg':''}">资金加速 ${x.acc>0?'+':''}${x.acc}</span><span class="tiny">${a?'5m '+(a.pct>=0?'+':'')+a.pct.toFixed(2)+'%':'5m 积累中'}</span></div></div><div class="right"><div class="pct ${clsPct(x.pct)}">${x.pct>=0?'+':''}${x.pct.toFixed(2)}%</div><div class="scorepill ${l[1]}">${l[0]} ${x.score}</div></div></div>`}).join('')||'<div class="empty">当前没有达到启动阈值的标的</div>'}
function renderRisks(){const risks=state[market].stocks.map(x=>({...x,acc:accelScore(x)})).filter(x=>(x.pct>7&&x.acc<-3)||(x.pct<0&&x.amount>5)||(x.score>85&&x.acc<-8)).slice(0,5);document.getElementById('riskList').innerHTML=(risks.length?risks:[{name:'暂无明显高危个股',code:'',pct:0,score:65,amount:0,turn:0,acc:0}]).map(x=>`<div class="row"><div class="rank">!</div><div><div class="name">${x.name}</div><div class="meta">${x.code?`资金加速 ${x.acc>0?'+':''}${x.acc} · `:''}${x.pct>7?'高位放量后减速':'注意巨量滞涨/冲高回落'}</div></div><div class="right"><div class="scorepill bad">风险</div></div></div>`).join('')}
function renderFlow(){const sec=state[market].sectors.map(x=>({...x,a5:accelForSector(x,5)})).sort((a,b)=>((b.a5?.score||0)+b.score*.25)-((a.a5?.score||0)+a.score*.25));const stocks=state[market].stocks.map(x=>({...x,acc:accelScore(x)})).sort((a,b)=>b.acc-a.acc);const s1=sec[0],s2=sec[1],l1=stocks[0],l2=stocks[1];document.getElementById('flowPath').innerHTML=[s1&&`<span class="node hot">${s1.name}</span>`,s1&&'<span class="arrow">→</span>',l1&&`<span class="node">${l1.name}</span>`,l2&&'<span class="arrow">→</span>',l2&&`<span class="node">${l2.name}</span>`,s2&&'<span class="arrow">→</span>',s2&&`<span class="node">${s2.name}</span>`].filter(Boolean).join('')||'积累行情快照后生成路径';document.getElementById('flowList').innerHTML=sec.slice(0,8).map((x,i)=>`<div class="row"><div class="rank">${i+1}</div><div><div class="name">${x.name}</div><div class="meta">潮汐 ${x.score} · 5m ${x.a5?(x.a5.score>=0?'+':'')+x.a5.score:'积累中'} · 涨幅 ${x.pct>=0?'+':''}${x.pct.toFixed(2)}%</div></div><div class="right"><div class="scorepill ${accelClass(x.a5)==='good'?'':'mid'}">${accelText(x.a5)}</div></div></div>`).join('')||'<div class="empty">暂无轮动数据</div>'}
function nightScore(x){const acc=accelScore(x);let s=x.score+acc*.35;if(x.pct>0&&x.pct<5)s+=8;if(x.pct>=8)s-=18;if(x.turn>2&&x.turn<15)s+=4;return Math.round(clamp(s,0,99))}
function renderNight(){const arr=state[market].stocks.map(x=>({...x,acc:accelScore(x),night:nightScore(x)})).filter(x=>x.pct>-1&&x.pct<6&&x.score>=72).sort((a,b)=>b.night-a.night).slice(0,12);document.getElementById('nightList').innerHTML=arr.map((x,i)=>`<div class="row tap" onclick="toggleWatch('${x.code}')"><div class="rank">${i+1}</div><div><div class="name">${x.name} <span style="font-size:10px;color:#6f829f">${x.code}</span></div><div class="meta">尚未高潮 · 资金加速 ${x.acc>0?'+':''}${x.acc} · 换手 ${x.turn.toFixed(1)}%</div></div><div class="right"><div class="pct ${clsPct(x.pct)}">${x.pct>=0?'+':''}${x.pct.toFixed(2)}%</div><div class="scorepill ${x.night>=85?'':'mid'}">前夜 ${x.night}</div></div></div>`).join('')||'<div class="empty">暂未发现符合“未大涨 + 资金开始集中”的标的</div>'}
function getWatch(){try{return JSON.parse(localStorage.getItem(WATCH_KEY)||'[]')}catch(e){return []}}
function isWatched(code){return getWatch().includes(String(code))}
function toggleWatch(code){let w=getWatch(),c=String(code);w=w.includes(c)?w.filter(x=>x!==c):[c,...w].slice(0,50);localStorage.setItem(WATCH_KEY,JSON.stringify(w));renderStocks();renderWatch()}
function addWatch(){const v=document.getElementById('watchInput').value.trim();if(!v)return;let w=getWatch();if(!w.includes(v))w=[v,...w].slice(0,50);localStorage.setItem(WATCH_KEY,JSON.stringify(w));document.getElementById('watchInput').value='';renderWatch()}
function renderWatch(){const w=getWatch(),all=[...state.A.stocks,...state.HK.stocks],map=new Map(all.map(x=>[String(x.code),x]));document.getElementById('watchList').innerHTML=w.map(code=>{const x=map.get(String(code));if(!x)return `<div class="row tap" onclick="toggleWatch('${code}')"><div class="rank">★</div><div><div class="name">${code}</div><div class="meta">当前行情列表未覆盖，点此移除</div></div><div class="right"><div class="scorepill mid">自选</div></div></div>`;const a=market==='A'||market==='HK'?accelScore(x):0;return `<div class="row tap" onclick="toggleWatch('${code}')"><div class="rank">★</div><div><div class="name">${x.name} <span style="font-size:10px;color:#6f829f">${x.code}</span></div><div class="meta">资金分 ${x.score} · 加速 ${a>0?'+':''}${a} · 成交 ${fmtAmt(x.amount)}</div></div><div class="right"><div class="pct ${clsPct(x.pct)}">${x.pct>=0?'+':''}${x.pct.toFixed(2)}%</div><div class="scorepill">已收藏</div></div></div>`}).join('')||'<div class="empty">还没有自选。可以在雷达或“启动前夜”点股票收藏。</div>'}
async function refreshAll(){document.getElementById('liveBadge').textContent='刷新中';document.getElementById('liveBadge').className='live off';await loadMarket(market);saveHist();render()}
if('serviceWorker' in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});
(async()=>{await Promise.all([loadMarket('A'),loadMarket('HK')]);saveHist();render()})();