// V2.3 accumulation scanner: gradual sector + stock inflow, avoiding sudden spikes.
(function(){
const style=document.createElement('style');style.textContent='.subtabs{grid-template-columns:repeat(5,1fr)!important}.nav{grid-template-columns:repeat(5,1fr)!important}.buildHero{background:linear-gradient(135deg,#11231c,#101a28);border:1px solid #244334;border-radius:18px;padding:14px;margin-bottom:10px}.buildHero b{font-size:20px}.buildLegend{font-size:10px;color:#8297b3;line-height:1.6;margin-top:5px}.buildRow{border-color:#274235}.buildTag{display:inline-block;font-size:9px;padding:3px 6px;border-radius:8px;background:#173127;color:#82e7b5;margin-right:5px;margin-top:5px}.buildTag.warn{background:#302714;color:#f2cf76}.buildTag.hot{background:#351d22;color:#ff9daa}.sectorMini{font-size:10px;color:#8ea0bc;margin-top:4px}';document.head.appendChild(style);
const subtabs=document.querySelector('.subtabs');if(subtabs&&!document.getElementById('tabBuild')){const b=document.createElement('button');b.id='tabBuild';b.textContent='建仓';b.onclick=()=>showTab('build');subtabs.insertBefore(b,document.getElementById('tabWatch'))}
const app=document.querySelector('.app');if(app&&!document.getElementById('panelBuild')){const p=document.createElement('div');p.id='panelBuild';p.className='hide';p.innerHTML='<div class="section"><div class="st"><h2>建仓雷达</h2><span>板块 + 个股同步温和流入</span></div><div class="buildHero"><b>寻找“慢慢进来”的钱</b><div class="buildLegend">优先：板块5/30分钟持续改善 + 个股资金同步抬升 + 涨幅克制 + 量比温和。<br>排除：突然爆拉、短时急冲、高位放量加速。</div></div><div id="buildList" class="list"><div class="empty">正在准备建仓扫描…</div></div></div>';app.insertBefore(p,app.querySelector('.notice'))}
const nav=document.querySelector('.nav');if(nav&&!document.getElementById('navBuild')){const b=document.createElement('button');b.id='navBuild';b.innerHTML='<span class="ico">◒</span>建仓';b.onclick=()=>showTab('build');nav.insertBefore(b,document.getElementById('navWatch'))}
const oldShowTab=showTab;showTab=function(t){if(t!=='build'){oldShowTab(t);document.getElementById('panelBuild')?.classList.add('hide');document.getElementById('tabBuild')?.classList.remove('active');document.getElementById('navBuild')?.classList.remove('active');return}currentTab='build';['radar','flow','night','watch'].forEach(x=>{document.getElementById('panel'+cap(x))?.classList.add('hide');document.getElementById('tab'+cap(x))?.classList.remove('active');document.getElementById('nav'+cap(x))?.classList.remove('active')});document.getElementById('panelBuild')?.classList.remove('hide');document.getElementById('tabBuild')?.classList.add('active');document.getElementById('navBuild')?.classList.add('active');scanBuild()}
function memberUrl(code){return `${EM}?pn=1&pz=80&po=1&np=1&fltt=2&invt=2&fid=f6&fs=${encodeURIComponent('b:'+code)}&fields=f12,f14,f2,f3,f5,f6,f8,f10,f62,f184`}
function sHist(sec,mins){const s=nearestSnapshot(market,mins);if(!s||!s.sectors[sec.name])return null;const p=s.sectors[sec.name];return {pct:sec.pct-p.pct,score:sec.score-p.score,amount:sec.amount-p.amount}}
function gradualSector(sec){const a5=sHist(sec,5),a30=sHist(sec,30);let score=50+sec.score*.22;const p5=a5?.pct??0,p30=a30?.pct??0,s5=a5?.score??0,s30=a30?.score??0;if(a5){score+=clamp(s5,-8,10)*1.4+clamp(p5,-1,1.8)*8}if(a30){score+=clamp(s30,-12,16)*.8+clamp(p30,-2,3)*4}if(sec.pct>4.5)score-=18;if(sec.pct>7)score-=25;if(p5>1.8||s5>14)score-=18;if(p5<-0.5||s5<-4)score-=14;return Math.round(clamp(score,0,99))}
function stockBuildScore(x,secScore){const a5=accelForStock(x,5),a30=accelForStock(x,30);let s=secScore*.45+x.score*.4;const p5=a5?.pct??0,p30=a30?.pct??0,sc5=a5?.score??0,sc30=a30?.score??0;if(a5)s+=clamp(sc5,-8,9)*1.1+clamp(p5,-.8,1.2)*7;if(a30)s+=clamp(sc30,-12,14)*.55+clamp(p30,-1.5,2.5)*3.5;if(x.pct>=-.5&&x.pct<=3.8)s+=10;else if(x.pct>5)s-=20;if(x.pct>8)s-=25;if(x.vr>=1&&x.vr<=2.4)s+=8;else if(x.vr>3.5)s-=12;if(x.turn>=1&&x.turn<=12)s+=5;if(p5>1.8||sc5>14)s-=18;if(p5<-.6||sc5<-5)s-=16;return Math.round(clamp(s,0,99))}
function phase(x,score){const a5=accelForStock(x,5);const v=(a5?.score||0)+(a5?.pct||0)*5;if(score>=86&&x.pct<3.5&&v>0)return '明显建仓';if(score>=78&&v>=0)return '持续吸筹';if(score>=70)return '早期观察';return '弱'}
async function scanBuild(){const box=document.getElementById('buildList');if(!box)return;box.innerHTML='<div class="empty">正在联动扫描强板块与成分股…</div>';if(!state[market].live){box.innerHTML='<div class="empty">当前是演示数据，建仓雷达不输出模拟结论。公开行情恢复后自动扫描。</div>';return}const secs=state[market].sectors.filter(x=>x.code).map(x=>({...x,build:gradualSector(x)})).filter(x=>x.build>=60&&x.pct<7).sort((a,b)=>b.build-a.build).slice(0,6);let rows=[];for(const sec of secs){try{const r=await jsonp(memberUrl(sec.code),9000);const members=normalizeStocks(r?.data?.diff).slice(0,35);for(const x of members){const bs=stockBuildScore(x,sec.build);if(bs>=68&&x.pct<6)rows.push({...x,build:bs,sector:sec.name,sectorBuild:sec.build,phase:phase(x,bs)})}}catch(e){}}
rows=rows.sort((a,b)=>b.build-a.build).slice(0,15);if(!rows.length){box.innerHTML='<div class="empty">暂时没有出现“板块与个股同步、且未突然爆拉”的明显建仓痕迹。这个结果宁缺毋滥。</div>';return}box.innerHTML=rows.map((x,i)=>{const a5=accelForStock(x,5),a30=accelForStock(x,30);const cls=x.build>=86?'':'mid';return `<div class="row buildRow"><div class="rank">${i+1}</div><div><div class="name">${x.name} <span style="font-size:10px;color:#6f829f">${x.code}</span></div><div class="sectorMini">所属 ${x.sector} · 板块建仓 ${x.sectorBuild}</div><div class="meta">成交 ${fmtAmt(x.amount)} · 换手 ${x.turn.toFixed(1)}% · 量比 ${x.vr.toFixed(1)} · 涨幅 ${x.pct>=0?'+':''}${x.pct.toFixed(2)}%</div><div><span class="buildTag">${x.phase}</span><span class="buildTag warn">5m ${a5?(a5.score>=0?'+':'')+a5.score:'积累中'}</span><span class="buildTag warn">30m ${a30?(a30.score>=0?'+':'')+a30.score:'积累中'}</span></div></div><div class="right"><div class="scorepill ${cls}">建仓 ${x.build}</div></div></div>`}).join('')}
const oldRender=render;render=function(){oldRender();if(currentTab==='build')scanBuild()}
})();