// V2.8 oversold rebound scanner: active A/HK stocks + daily K-line confirmation.
(function(){
if(window.__fundRadar_rebound)return;window.__fundRadar_rebound=true;
const UT='fa5fd1943c7b386f172d6893dbbd1d0c';
const KH='https://push2his.eastmoney.com/api/qt/stock/kline/get';
const style=document.createElement('style');style.textContent='.subtabs{grid-template-columns:repeat(6,1fr)!important}.nav{grid-template-columns:repeat(6,1fr)!important}.reboundHero{background:linear-gradient(135deg,#241d12,#101a28);border:1px solid #493a20;border-radius:18px;padding:14px;margin-bottom:10px}.reboundHero b{font-size:20px}.reboundLegend{font-size:10px;color:#91a1b8;line-height:1.65;margin-top:5px}.reboundTag{display:inline-block;font-size:9px;padding:3px 6px;border-radius:8px;background:#302714;color:#f2cf76;margin-right:5px;margin-top:5px}.reboundTag.good{background:#123125;color:#75e5b0}.reboundTag.hot{background:#351d22;color:#ff9daa}.reboundRow{border-color:#40351f}';document.head.appendChild(style);
const subtabs=document.querySelector('.subtabs');if(subtabs&&!document.getElementById('tabRebound')){const b=document.createElement('button');b.id='tabRebound';b.textContent='反弹';b.onclick=()=>showTab('rebound');subtabs.insertBefore(b,document.getElementById('tabWatch'))}
const app=document.querySelector('.app');if(app&&!document.getElementById('panelRebound')){const p=document.createElement('div');p.id='panelRebound';p.className='hide';p.innerHTML='<div class="section"><div class="st"><h2>超跌反弹雷达</h2><span>跌得够深，但不接飞刀</span></div><div class="reboundHero"><b>找“跌透后开始拐头”的票</b><div class="reboundLegend">核心看：RSI14超卖/低位、距20日高点回撤、接近20日低位、近5日止跌、量能温和回升、当日资金不再恶化。<br>排除：单日突然爆拉、极端放量、仍在加速下跌。优先高成交活跃股。</div></div><div id="reboundList" class="list"><div class="empty">点击本页后开始扫描…</div></div></div>';app.insertBefore(p,app.querySelector('.notice'))}
const nav=document.querySelector('.nav');if(nav&&!document.getElementById('navRebound')){const b=document.createElement('button');b.id='navRebound';b.innerHTML='<span class="ico">↺</span>反弹';b.onclick=()=>showTab('rebound');nav.insertBefore(b,document.getElementById('navWatch'))}
const prevShowTab=showTab;showTab=function(t){if(t!=='rebound'){prevShowTab(t);document.getElementById('panelRebound')?.classList.add('hide');document.getElementById('tabRebound')?.classList.remove('active');document.getElementById('navRebound')?.classList.remove('active');return}currentTab='rebound';['radar','flow','night','build','watch'].forEach(x=>{document.getElementById('panel'+cap(x))?.classList.add('hide');document.getElementById('tab'+cap(x))?.classList.remove('active');document.getElementById('nav'+cap(x))?.classList.remove('active')});document.getElementById('panelRebound')?.classList.remove('hide');document.getElementById('tabRebound')?.classList.add('active');document.getElementById('navRebound')?.classList.add('active');scanRebound()}
function secidOf(code,m){const c=String(code);if(m==='HK')return `116.${c.padStart(5,'0')}`;return `${/^(5|6|7|9)/.test(c)?1:0}.${c}`}
function kUrl(code,m){return `${KH}?secid=${encodeURIComponent(secidOf(code,m))}&fields1=f1,f2,f3&fields2=f51,f52,f53,f54,f55,f56,f57,f58,f59,f60,f61&klt=101&fqt=1&end=20500101&lmt=35&ut=${UT}`}
function rsi14(c){if(c.length<15)return null;let g=0,l=0;for(let i=c.length-14;i<c.length;i++){const d=c[i]-c[i-1];if(d>0)g+=d;else l-=d}if(l===0)return 100;const rs=(g/14)/(l/14);return 100-100/(1+rs)}
function parseK(r){return (r?.data?.klines||[]).map(s=>{const a=String(s).split(',');return {d:a[0],o:n(a[1]),c:n(a[2]),h:n(a[3]),l:n(a[4]),v:n(a[5]),amt:n(a[6]),pct:n(a[8]),turn:n(a[10])}}).filter(x=>x.c>0)}
function bulkUrl(m){const fs=m==='A'?'m:0+t:6,m:0+t:80,m:1+t:2,m:1+t:23':'m:128+t:3,m:128+t:4,m:128+t:1,m:128+t:2';return `${EM}?pn=1&pz=180&po=1&np=1&fltt=2&invt=2&fid=f6&fs=${encodeURIComponent(fs)}&fields=f12,f14,f2,f3,f5,f6,f8,f10,f62,f184`}
function rawStock(x,m){return {code:String(x.f12||''),name:String(x.f14||''),market:m,price:n(x.f2),pct:n(x.f3),amount:bn(x.f6),turn:n(x.f8),vr:n(x.f10),flow:n(x.f62),flowPct:n(x.f184)}}
function evaluate(x,k){if(k.length<21)return null;const closes=k.map(z=>z.c),vols=k.map(z=>z.v),rsi=rsi14(closes);const last=k[k.length-1],prev=k[k.length-2],w20=k.slice(-20),high20=Math.max(...w20.map(z=>z.h)),low20=Math.min(...w20.map(z=>z.l));const draw=(last.c/high20-1)*100,nearLow=(last.c/low20-1)*100,ret5=(last.c/k[Math.max(0,k.length-6)].c-1)*100;const v3=vols.slice(-3).reduce((a,b)=>a+b,0)/3,v20=vols.slice(-20).reduce((a,b)=>a+b,0)/20,volLift=v20?v3/v20:1;let s=34;if(rsi>=24&&rsi<=36)s+=24;else if(rsi>36&&rsi<=43)s+=15;else if(rsi<24)s+=9;else if(rsi>50)s-=12;const dd=-draw;if(dd>=10&&dd<=26)s+=20;else if(dd>=6)s+=11;else if(dd>26)s+=8;if(nearLow<=5)s+=10;else if(nearLow<=10)s+=6;if(ret5>=-6&&ret5<=3)s+=9;else if(ret5>6)s-=15;if(volLift>=.85&&volLift<=2.2)s+=9;else if(volLift>3.5)s-=12;if(x.pct>=-2&&x.pct<=3.2)s+=8;else if(x.pct>5)s-=22;if(x.flowPct>0)s+=6;else if(x.flowPct<-5)s-=6;if(last.c>prev.c)s+=6;if(k.length>=3&&last.c>prev.c&&prev.c>=k[k.length-3].c)s+=5;if(last.pct<-5)s-=18;if(rsi<18&&last.c<prev.c)s-=20;s=Math.round(clamp(s,0,99));return {...x,rebound:s,rsi,draw,nearLow,ret5,volLift,turn:last.turn||x.turn,turning:last.c>prev.c}}
function phase(x){if(x.rebound>=85&&x.turning&&x.rsi<=43)return '反弹临界';if(x.rebound>=76)return '拐点观察';if(x.rebound>=66)return '超跌潜伏';return '弱'}
let scanId=0;
async function scanRebound(){const id=++scanId,m=market;const active=()=>id===scanId&&market===m&&currentTab==='rebound';const box=document.getElementById('reboundList');if(!box)return;box.innerHTML='<div class="empty">正在读取活跃股日K，计算 RSI / 20日回撤 / 止跌信号…</div>';if(state[market].stale){box.innerHTML='<div class="empty">行情已过期，请刷新雷达后再扫描；不使用旧行情生成当前反弹结论。</div>';return}if(!state[market].live){box.innerHTML='<div class="empty">当前是演示数据，超跌反弹雷达不输出模拟结论。公开行情恢复后再扫描。</div>';return}try{const q=await jsonp(bulkUrl(m),12000);if(!active())return;const diff=q?.data?.diff;if(q?.rc&&q.rc!==0||!diff)throw new Error('股票列表未返回');const items=Array.isArray(diff)?diff:Object.values(diff);if(!items.length)throw new Error('股票列表为空');const raw=items.map(z=>rawStock(z,m)).filter(x=>x.code&&x.name&&!/ST|退/.test(x.name)&&x.amount>=.8&&x.pct<4.5&&x.pct>-9.8);const pool=raw.slice(0,42);const out=[];let failed=0,short=0,valid=0;for(let i=0;i<pool.length;i+=7){const batch=pool.slice(i,i+7);const rs=await Promise.allSettled(batch.map(async x=>evaluate(x,parseK(await jsonp(kUrl(x.code,m),9000)))));if(!active())return;rs.forEach(r=>{if(r.status==='rejected')failed++;else if(!r.value)short++;else{valid++;if(r.value.rebound>=64)out.push(r.value)}})}const summary=`已读取 ${items.length} 只活跃股 · 初筛后扫描 ${pool.length} 只 · 日K有效 ${valid} · 请求失败 ${failed} · 日K不足 ${short}`;out.sort((a,b)=>b.rebound-a.rebound);const rows=out.slice(0,15);if(!rows.length){box.innerHTML='<div class="empty">'+summary+'<br>'+(!pool.length?'当前活跃股样本未通过成交额与涨跌幅初筛。':!valid?'日K数据不可用，无法判断反弹候选，请稍后刷新。':failed||short?'数据不完整：已取得日K的样本暂无候选，不能据此判断全部扫描股票。':'本次有效样本中暂无达到反弹评分阈值的候选。')+'</div>';return}box.innerHTML='<div class="mini">'+summary+'；仅为活跃股样本，非全市场。'+(failed||short?'部分数据缺失，结果不完整。':'')+'</div>'+rows.map((x,i)=>`<div class="row reboundRow tap" onclick="toggleWatch('${x.code}')"><div class="rank">${i+1}</div><div><div class="name">${x.name} <span style="font-size:10px;color:#6f829f">${x.code}</span> <span class="star ${isWatched(x.code)?'on':''}">★</span></div><div class="meta">RSI14 ${x.rsi.toFixed(0)} · 20日高点回撤 ${x.draw.toFixed(1)}% · 距20日低点 +${x.nearLow.toFixed(1)}%</div><div class="meta">5日 ${x.ret5>=0?'+':''}${x.ret5.toFixed(1)}% · 3日/20日量能 ${x.volLift.toFixed(2)}x · 今日 ${x.pct>=0?'+':''}${x.pct.toFixed(2)}%</div><div><span class="reboundTag ${x.rebound>=85?'good':''}">${phase(x)}</span><span class="reboundTag">${x.turning?'已拐头':'等拐头'}</span></div></div><div class="right"><div class="scorepill ${x.rebound>=85?'':'mid'}">反弹 ${x.rebound}</div></div></div>`).join('')}catch(e){if(!active())return;box.innerHTML='<div class="empty">超跌扫描接口暂时没有返回完整日K。稍后点“刷新雷达”再试。</div>'}}
const prevRender=render;render=function(){prevRender();if(currentTab==='rebound')scanRebound()}
})();

