// V2.13: A-share review fallback using the same verified A-share universe as the live radar.
(function(){
'use strict';
const AF='m:0+t:6,m:0+t:80,m:1+t:2,m:1+t:23';
const U='https://push2.eastmoney.com/api/qt/clist/get';
let busy=false,last=null;
function req(url,timeout=12000){return new Promise((ok,fail)=>{const cb='arf_'+Date.now()+'_'+Math.random().toString(36).slice(2),s=document.createElement('script');let t;const done=(e,d)=>{clearTimeout(t);s.remove();delete window[cb];e?fail(e):ok(d)};window[cb]=d=>done(null,d);s.onerror=()=>done(new Error('A股接口连接失败'));t=setTimeout(()=>done(new Error('A股接口超时')),timeout);s.src=url+'&cb='+cb+'&_='+Date.now();document.body.appendChild(s)})}
function url(page){return U+'?'+new URLSearchParams({pn:page,pz:200,po:0,np:1,fltt:2,invt:2,fid:'f12',fs:AF,fields:'f12,f14,f3,f6,f8,f10,f62,f184'})}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function n(v){v=Number(v);return Number.isFinite(v)?v:0}
function money(v){return (n(v)/1e8).toFixed(1)+'亿'}
async function loadA(){const rows=[],seen=new Set();let total=0;for(let p=1;p<=35;p++){const r=await req(url(p));if(!r||r.rc!==0||!r.data)throw new Error('A股接口未返回数据');if(!total)total=n(r.data.total);const batch=Array.isArray(r.data.diff)?r.data.diff:Object.values(r.data.diff||{});for(const x of batch){if(x&&x.f12&&!seen.has(x.f12)){seen.add(x.f12);rows.push(x)}}if(total&&rows.length>=total)break;if(!batch.length)break}if(rows.length<100)throw new Error('A股有效样本不足');return {rows,total}}
function renderA(data){const box=document.getElementById('reviewBody'),status=document.getElementById('reviewStatus');if(!box||currentTab!=='review'||market!=='A')return;const valid=data.rows.filter(x=>x&&x.f14&&Number.isFinite(Number(x.f3))&&n(x.f6)>0),up=valid.filter(x=>n(x.f3)>0).length,down=valid.filter(x=>n(x.f3)<0).length,flat=valid.length-up-down,amt=valid.reduce((s,x)=>s+n(x.f6),0),leaders=valid.slice().sort((a,b)=>((n(b.f3)*2+Math.log10(Math.max(1,n(b.f6)))+(n(b.f62)>0?1:0))-(n(a.f3)*2+Math.log10(Math.max(1,n(a.f6)))+(n(a.f62)>0?1:0)))).slice(0,8),strong=valid.slice().sort((a,b)=>n(b.f3)-n(a.f3)).slice(0,8),weak=valid.slice().sort((a,b)=>n(a.f3)-n(b.f3)).slice(0,8),ratio=up/Math.max(1,valid.length),emotion=ratio>=.6?'偏强':ratio<=.4?'偏弱':'分歧';const rows=(arr)=>'<div class="list">'+arr.map((x,i)=>'<div class="reviewRow"><div><b>'+(i+1)+'. '+esc(x.f14)+'</b><div class="meta">'+esc(x.f12)+' · 成交 '+money(x.f6)+'</div></div><div class="right '+(n(x.f3)>=0?'up':'down')+'">'+(n(x.f3)>=0?'+':'')+n(x.f3).toFixed(2)+'%</div></div>').join('')+'</div>';box.innerHTML='<div class="card"><strong>A股 · 最近交易日实盘快照</strong><div class="mini">A股复盘主接口失败后，已切换备用分页线路。覆盖 '+valid.length+' / '+(data.total||'未知')+' 只；这是实际行情，不是演示数据。</div></div><section class="section"><div class="st"><h2>市场概览</h2></div><div class="reviewMetrics"><div class="metric"><b>'+up+'</b><span>上涨</span></div><div class="metric"><b>'+down+'</b><span>下跌</span></div><div class="metric"><b>'+flat+'</b><span>平盘</span></div><div class="metric"><b>'+money(amt)+'</b><span>样本成交额</span></div></div></section><section class="section"><div class="st"><h2>市场情绪：'+emotion+'</h2></div><div class="card mini">上涨占比 '+(ratio*100).toFixed(1)+'%。按涨跌广度判断，不使用模拟数据。</div></section><section class="section"><div class="st"><h2>涨幅前列</h2></div>'+rows(strong)+'</section><section class="section"><div class="st"><h2>跌幅前列</h2></div>'+rows(weak)+'</section><section class="section"><div class="st"><h2>核心强势候选</h2></div><div class="mini">按涨幅、成交额和正净流入综合排序。</div>'+rows(leaders)+'</section><p class="notice">备用线路先保证 A 股复盘可用。板块 Top5 与完整资金板块排名仍优先由主复盘接口提供；主接口恢复后会自动回到完整版。</p>';status.textContent='A股备用实盘快照已更新'}
async function fallback(){if(busy||market!=='A'||currentTab!=='review')return;busy=true;const status=document.getElementById('reviewStatus');if(status)status.textContent='A股主复盘未取到，切换备用实盘线路…';try{last=await loadA();renderA(last)}catch(e){if(status)status.textContent=e.message+'；A股暂无可用快照'}finally{busy=false}}
const oldShow=showTab;showTab=function(t){oldShow(t);if(t==='review'&&market==='A')setTimeout(()=>{const text=document.getElementById('reviewStatus')?.textContent||'';if(!document.getElementById('reviewBody')?.textContent.includes('A股 ·')||/暂无可用|失败|无法核实|没有可核实/.test(text))fallback()},900)};
const oldSwitch=switchMarket;switchMarket=function(m){oldSwitch(m);if(currentTab==='review'&&m==='A')setTimeout(fallback,900)};
document.getElementById('reviewRefresh')?.addEventListener('click',()=>{if(market==='A')setTimeout(fallback,700)});
})();