(function(){
const style=document.createElement('style');style.textContent='.sectorCard{cursor:pointer;position:relative}.sectorCard:after{content:"›";position:absolute;right:12px;top:12px;color:#60738f;font-size:20px}.modal{position:fixed;inset:0;z-index:50;background:rgba(2,7,14,.76);backdrop-filter:blur(10px);display:flex;align-items:flex-end;justify-content:center}.modal.hide{display:none}.sheet{width:min(600px,100%);max-height:82vh;overflow:auto;background:#0b1525;border:1px solid #263752;border-radius:24px 24px 0 0;padding:16px 14px calc(env(safe-area-inset-bottom) + 18px)}.sheetHead{display:flex;justify-content:space-between;gap:10px;align-items:flex-start;position:sticky;top:0;background:#0b1525;padding:10px 0 12px;z-index:2}.sheetHead h3{margin:0;font-size:20px}.closeBtn{border:1px solid var(--line);background:#142239;color:#dbe8fb;border-radius:12px;min-width:44px;min-height:44px}.groupTitle{font-size:12px;color:#91a6c6;margin:14px 2px 7px}.leaderRow{display:grid;grid-template-columns:1fr auto;gap:10px;background:var(--panel);border:1px solid var(--line);border-radius:14px;padding:11px;margin-bottom:7px}.leaderTag{display:inline-block;font-size:10px;padding:3px 7px;border-radius:999px;margin-left:5px;background:#38211e;color:#ffb0a6}.leaderTag.core{background:#202a43;color:#a9c8ff}.leaderTag.strong{background:#173127;color:#82e7b5}.sectorHint{font-size:10px;color:#70839e;margin-top:5px}';document.head.appendChild(style);
const modal=document.createElement('div');modal.id='sectorModal';modal.className='modal hide';modal.setAttribute('aria-hidden','true');modal.innerHTML='<div class="sheet"><div class="sheetHead"><div><h3 id="sectorTitle">板块成分股</h3><div id="sectorSub" class="mini">正在读取成分股</div></div><button class="closeBtn" id="sectorClose" aria-label="关闭">×</button></div><div id="sectorMembers"></div></div>';document.body.appendChild(modal);document.getElementById('sectorClose').addEventListener('click',closeSector);
function sectorMembersUrl(code){return `${EM}?pn=1&pz=80&po=1&np=1&fltt=2&invt=2&fid=f6&fs=${encodeURIComponent('b:'+code)}&fields=f12,f14,f2,f3,f5,f6,f8,f10,f62,f184`}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
renderSectors=function(){const d=state[market].sectors;document.getElementById('sectorGrid').innerHTML=d.slice(0,6).map(x=>{const a=accelForSector(x,5);return `<div class="card sectorCard" data-code="${esc(x.code)}" data-name="${esc(x.name)}"><span class="accel">${accelText(a)}</span><strong>${esc(x.name)}</strong><div class="${clsPct(x.pct)}" style="font-size:22px;font-weight:800">${x.pct>=0?'+':''}${x.pct.toFixed(2)}%</div><div class="tag ${x.score>=85?'hot':x.score>=76?'good':'warn'}">潮汐 ${x.score}</div><div class="tag ${accelClass(a)}">5m ${a?(a.score>=0?'+':'')+a.score:'--'}</div><div class="flowbar"><i style="width:${clamp(x.score,5,100)}%"></i></div><div class="sectorHint">点击查看成分股与龙头</div></div>`}).join('')||'<div class="empty">暂无板块数据</div>';document.querySelectorAll('.sectorCard').forEach(el=>el.addEventListener('click',()=>openSector(el.dataset.code,el.dataset.name)))};
function leaderBadge(i){return i===0?'<span class="leaderTag">龙头</span>':i<3?'<span class="leaderTag core">核心强势</span>':i<6?'<span class="leaderTag strong">强势</span>':''}
function memberRow(x,i){return `<div class="leaderRow"><div><div class="name">${i+1}. ${esc(x.name)} <span style="font-size:10px;color:#6f829f">${esc(x.code)}</span>${leaderBadge(i)}</div><div class="meta">成交 ${fmtAmt(x.amount)} · 换手 ${x.turn.toFixed(1)}% · 量比 ${x.vr.toFixed(1)} · 资金分 ${x.score}</div></div><div class="right"><div class="pct ${clsPct(x.pct)}">${x.pct>=0?'+':''}${x.pct.toFixed(2)}%</div></div></div>`}
async function openSector(code,name){const modal=document.getElementById('sectorModal'),box=document.getElementById('sectorMembers');document.getElementById('sectorTitle').textContent=name+' · 成分股';document.getElementById('sectorSub').textContent='按量价、成交活跃度和资金强度识别龙头';box.innerHTML='<div class="empty">正在读取板块成分股…</div>';modal.classList.remove('hide');modal.setAttribute('aria-hidden','false');document.body.style.overflow='hidden';if(!code){box.innerHTML='<div class="empty">当前为演示板块，实时成分股需公开行情连接成功后显示。</div>';return}try{const r=await jsonp(sectorMembersUrl(code));let arr=normalizeStocks(r?.data?.diff);if(!arr.length)throw new Error('empty');arr=arr.sort((a,b)=>(b.score+b.pct*.8)-(a.score+a.pct*.8));const groups=[['👑 龙头',arr.slice(0,1)],['🔥 核心强势',arr.slice(1,3)],['⚡ 强势梯队',arr.slice(3,6)],['成分股 Top 20',arr.slice(6,20)]];box.innerHTML=groups.filter(g=>g[1].length).map(g=>`<div class="groupTitle">${g[0]}</div>${g[1].map(x=>memberRow(x,arr.indexOf(x))).join('')}`).join('');document.getElementById('sectorSub').textContent=`共读取 ${arr.length} 只活跃成分股 · 龙头按资金分+涨幅综合排序`}catch(e){box.innerHTML='<div class="empty">这个板块的免费接口暂未返回成分股。刷新后可重试；不会用模拟股票冒充实时成分股。</div>'}}
function closeSector(){const m=document.getElementById('sectorModal');m.classList.add('hide');m.setAttribute('aria-hidden','true');document.body.style.overflow=''}
document.getElementById('sectorModal')?.addEventListener('click',e=>{if(e.target.id==='sectorModal')closeSector()});
renderSectors();
})();