// V2.9 sector drilldown: paginated full constituent loading + leader/core/strong groups.
(function(){
const BOARD_UT='bd1d9ddb04089700cf9c27f6f7426281';
const style=document.createElement('style');style.textContent='.sectorCard{cursor:pointer;position:relative}.sectorCard:after{content:"›";position:absolute;right:12px;top:12px;color:#60738f;font-size:20px}.modal{position:fixed;inset:0;z-index:50;background:rgba(2,7,14,.76);backdrop-filter:blur(10px);display:flex;align-items:flex-end;justify-content:center}.modal.hide{display:none}.sheet{width:min(600px,100%);max-height:82vh;overflow:auto;background:#0b1525;border:1px solid #263752;border-radius:24px 24px 0 0;padding:16px 14px calc(env(safe-area-inset-bottom) + 18px)}.sheetHead{display:flex;justify-content:space-between;gap:10px;align-items:flex-start;position:sticky;top:0;background:#0b1525;padding:10px 0 12px;z-index:2}.sheetHead h3{margin:0;font-size:20px}.closeBtn{border:1px solid var(--line);background:#142239;color:#dbe8fb;border-radius:12px;min-width:44px;min-height:44px}.groupTitle{font-size:12px;color:#91a6c6;margin:14px 2px 7px}.leaderRow{display:grid;grid-template-columns:1fr auto;gap:10px;background:var(--panel);border:1px solid var(--line);border-radius:14px;padding:11px;margin-bottom:7px}.leaderTag{display:inline-block;font-size:10px;padding:3px 7px;border-radius:999px;margin-left:5px;background:#38211e;color:#ffb0a6}.leaderTag.core{background:#202a43;color:#a9c8ff}.leaderTag.strong{background:#173127;color:#82e7b5}.sectorHint{font-size:10px;color:#70839e;margin-top:5px}.memberCount{font-size:10px;color:#7f93af;margin:5px 2px 10px}';document.head.appendChild(style);
let modal=document.getElementById('sectorModal');if(modal)modal.remove();modal=document.createElement('div');modal.id='sectorModal';modal.className='modal hide';modal.setAttribute('aria-hidden','true');modal.innerHTML='<div class="sheet"><div class="sheetHead"><div><h3 id="sectorTitle">板块成分股</h3><div id="sectorSub" class="mini">正在读取成分股</div></div><button class="closeBtn" id="sectorClose" aria-label="关闭">×</button></div><div id="sectorMembers"></div></div>';document.body.appendChild(modal);
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function boardUrl(code,pn=1,pz=100){return `${EM}?pn=${pn}&pz=${pz}&po=1&np=1&ut=${BOARD_UT}&fltt=2&invt=2&fid=f3&fs=${encodeURIComponent('b:'+code)}&fields=f2,f3,f5,f6,f8,f10,f12,f13,f14,f62,f184`}
function asArray(diff){if(Array.isArray(diff))return diff;if(diff&&typeof diff==='object')return Object.values(diff);return []}
function normMembers(items){return asArray(items).filter(x=>x&&x.f12&&x.f14).map(x=>{const pseudo={f3:n(x.f3),f6:n(x.f6),f8:n(x.f8),f10:n(x.f10),f184:n(x.f184)};return {code:String(x.f12),name:String(x.f14),price:n(x.f2),pct:n(x.f3),amount:bn(x.f6),turn:n(x.f8),vr:n(x.f10),flow:n(x.f62),flowPct:n(x.f184),score:scoreStock(pseudo)}})}
async function fetchAllMembers(code){const pageSize=100,all=[],seen=new Set();let total=0;for(let pn=1;pn<=4;pn++){const r=await jsonp(boardUrl(code,pn,pageSize),10000);const batch=asArray(r?.data?.diff);if(pn===1)total=n(r?.data?.total);for(const z of batch){const k=String(z?.f12||'');if(k&&!seen.has(k)){seen.add(k);all.push(z)}}if(!batch.length)break;if(total&&all.length>=total)break;if(batch.length<pageSize)break}return {items:normMembers(all),total:total||all.length}}
renderSectors=function(){const d=state[market].sectors;document.getElementById('sectorGrid').innerHTML=d.slice(0,6).map(x=>{const a=accelForSector(x,5);return `<div class="card sectorCard" data-code="${esc(x.code)}" data-name="${esc(x.name)}"><span class="accel">${accelText(a)}</span><strong>${esc(x.name)}</strong><div class="${clsPct(x.pct)}" style="font-size:22px;font-weight:800">${x.pct>=0?'+':''}${x.pct.toFixed(2)}%</div><div class="tag ${x.score>=85?'hot':x.score>=76?'good':'warn'}">潮汐 ${x.score}</div><div class="tag ${accelClass(a)}">5m ${a?(a.score>=0?'+':'')+a.score:'--'}</div><div class="flowbar"><i style="width:${clamp(x.score,5,100)}%"></i></div><div class="sectorHint">点击查看完整成分股 · 龙头 · 强势梯队</div></div>`}).join('')||'<div class="empty">暂无板块数据</div>';document.querySelectorAll('.sectorCard').forEach(el=>el.addEventListener('click',()=>openSector(el.dataset.code,el.dataset.name)))};
function leaderBadge(i){return i===0?'<span class="leaderTag">👑 龙头</span>':i<3?'<span class="leaderTag core">🔥 核心强势</span>':i<6?'<span class="leaderTag strong">⚡ 强势</span>':''}
function memberRow(x,i){return `<div class="leaderRow"><div><div class="name">${i+1}. ${esc(x.name)} <span style="font-size:10px;color:#6f829f">${esc(x.code)}</span>${leaderBadge(i)}</div><div class="meta">成交 ${fmtAmt(x.amount)} · 换手 ${x.turn.toFixed(1)}% · 量比 ${x.vr.toFixed(1)} · 资金分 ${x.score}</div></div><div class="right"><div class="pct ${clsPct(x.pct)}">${x.pct>=0?'+':''}${x.pct.toFixed(2)}%</div></div></div>`}
async function openSector(code,name){const box=document.getElementById('sectorMembers');document.getElementById('sectorTitle').textContent=name+' · 成分股';document.getElementById('sectorSub').textContent='正在分页读取完整成分股…';box.innerHTML='<div class="empty">正在读取板块全部成分股并识别龙头…</div>';modal.classList.remove('hide');modal.setAttribute('aria-hidden','false');document.body.style.overflow='hidden';if(!code){box.innerHTML='<div class="empty">当前板块没有可用代码，无法读取实时成分股。</div>';return}try{const got=await fetchAllMembers(code);let arr=got.items;if(!arr.length)throw new Error('empty');arr.sort((a,b)=>(b.score+b.pct*.8+Math.log10(Math.max(.01,b.amount))*2)-(a.score+a.pct*.8+Math.log10(Math.max(.01,a.amount))*2));const show=arr.slice(0,40);const groups=[['👑 龙头',show.slice(0,1)],['🔥 核心强势',show.slice(1,3)],['⚡ 强势梯队',show.slice(3,6)],['其余活跃成分股',show.slice(6,40)]];box.innerHTML=`<div class="memberCount">接口共返回 ${arr.length}${got.total&&got.total!==arr.length?' / '+got.total:''} 只 · 当前展示前 ${show.length} 只</div>`+groups.filter(g=>g[1].length).map(g=>`<div class="groupTitle">${g[0]}</div>${g[1].map(x=>memberRow(x,show.indexOf(x))).join('')}`).join('');document.getElementById('sectorSub').textContent='按资金分 + 涨幅 + 成交活跃度综合识别龙头';}catch(e){box.innerHTML='<div class="empty">板块成分股接口本次没有返回完整数据。请稍后重试；不会拿两只股票冒充完整板块。</div>';document.getElementById('sectorSub').textContent='成分股读取失败'} }
function closeSector(){modal.classList.add('hide');modal.setAttribute('aria-hidden','true');document.body.style.overflow=''}
document.getElementById('sectorClose').addEventListener('click',closeSector);modal.addEventListener('click',e=>{if(e.target===modal)closeSector()});
renderSectors();
})();