// V2.23: server-generated A-share build/rebound candidates. Avoid iPhone cross-origin scan failures.
(function(){'use strict';
const RAW='https://raw.githubusercontent.com/maxzhou1986-debug/Maxzzz/main/fund-radar/data/signals-A.json';
const CDN='https://cdn.jsdelivr.net/gh/maxzhou1986-debug/Maxzzz@main/fund-radar/data/signals-A.json';
let cache=null,busy=false,restoring=false;
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function amt(v){return ((Number(v)||0)/1e8).toFixed(1)+'亿'}
async function get(){if(busy)return cache;busy=true;for(const u of ['./data/signals-A.json',CDN,RAW]){try{const r=await fetch(u+(u.includes('?')?'&':'?')+'ts='+Date.now(),{cache:'no-store',mode:'cors'});if(!r.ok)continue;const d=await r.json();if(d?.market==='A'&&(d.build?.length||d.rebound?.length)){cache=d;break}}catch(e){}}busy=false;return cache}
function buildHtml(d){const a=d.build||[];if(!a.length)return '<div data-server-signal="build" class="empty">服务器已扫描，但当前没有达到建仓观察阈值的股票。</div>';return '<div data-server-signal="build"><div class="mini">服务器实盘样本 '+(d.sample||0)+' 只 · '+esc(d.generatedAt||'')+'<br>量价/资金温和增强候选，不等同机构持仓证明。</div>'+a.slice(0,15).map((x,i)=>`<div class="row buildRow"><div class="rank">${i+1}</div><div><div class="name">${esc(x.name)} <span style="font-size:10px;color:#6f829f">${esc(x.code)}</span></div><div class="meta">成交 ${amt(x.amount)} · 换手 ${(Number(x.turn)||0).toFixed(1)}% · 量比 ${(Number(x.vr)||0).toFixed(1)} · 今日 ${(Number(x.pct)>=0?'+':'')+(Number(x.pct)||0).toFixed(2)}%</div><div><span class="buildTag">${esc(x.phase||'观察')}</span><span class="buildTag warn">资金 ${(Number(x.flow)||0)>=0?'+':''}${amt(x.flow)}</span></div></div><div class="right"><div class="scorepill">建仓 ${x.build}</div></div></div>`).join('')+'</div>'}
function reboundHtml(d){const a=d.rebound||[];if(!a.length)return '<div data-server-signal="rebound" class="empty">服务器已扫描，但当前没有达到超跌反弹阈值的股票。</div>';return '<div data-server-signal="rebound"><div class="mini">服务器日K扫描 · '+esc(d.generatedAt||'')+' · 不再依赖 iPhone 直连历史行情接口。</div>'+a.slice(0,15).map((x,i)=>`<div class="row reboundRow"><div class="rank">${i+1}</div><div><div class="name">${esc(x.name)} <span style="font-size:10px;color:#6f829f">${esc(x.code)}</span></div><div class="meta">RSI14 ${(Number(x.rsi)||0).toFixed(0)} · 20日高点回撤 ${(Number(x.draw)||0).toFixed(1)}% · 距20日低点 +${(Number(x.nearLow)||0).toFixed(1)}%</div><div class="meta">5日 ${(Number(x.ret5)>=0?'+':'')+(Number(x.ret5)||0).toFixed(1)}% · 量能 ${(Number(x.volLift)||0).toFixed(2)}x · 今日 ${(Number(x.pct)>=0?'+':'')+(Number(x.pct)||0).toFixed(2)}%</div><span class="reboundTag ${x.rebound>=80?'good':''}">${x.turning?'已拐头':'等拐头'}</span></div><div class="right"><div class="scorepill">反弹 ${x.rebound}</div></div></div>`).join('')+'</div>'}
async function paint(type){if(market!=='A'||currentTab!==type)return;const id=type==='build'?'buildList':'reboundList',box=document.getElementById(id);if(!box)return;const d=await get();if(!d||currentTab!==type||market!=='A')return;restoring=true;box.innerHTML=type==='build'?buildHtml(d):reboundHtml(d);setTimeout(()=>restoring=false,0)}
function repin(type){if(restoring||market!=='A'||currentTab!==type||!cache)return;const box=document.getElementById(type==='build'?'buildList':'reboundList');if(box&&!box.querySelector('[data-server-signal="'+type+'"]'))setTimeout(()=>paint(type),0)}
const oldShow=showTab;showTab=function(t){oldShow(t);if(t==='build'||t==='rebound')setTimeout(()=>paint(t),80)};
['build','rebound'].forEach(t=>{const b=document.getElementById(t==='build'?'buildList':'reboundList');if(b)new MutationObserver(()=>repin(t)).observe(b,{childList:true,subtree:true})});
setInterval(()=>{cache=null;if(currentTab==='build'||currentTab==='rebound')paint(currentTab)},90000);
})();
