// V2.7 watchlist resolver: fixed Eastmoney quote token; direct code lookup is primary.
const WATCH_DETAIL_KEY='fundRadarWatchDetailV27';
const EM_QUOTE='https://push2.eastmoney.com/api/qt/stock/get';
const EM_UT='fa5fd1943c7b386f172d6893dbfba10b';
function getWatchDetail(){try{return JSON.parse(localStorage.getItem(WATCH_DETAIL_KEY)||'{}')}catch(e){return {}}}
function saveWatchDetail(d){try{localStorage.setItem(WATCH_DETAIL_KEY,JSON.stringify(d))}catch(e){}}
function watchNormCode(v){return String(v||'').trim().toUpperCase().replace(/\.HK$/,'').replace(/[^0-9]/g,'')}
function watchMatch(items,q){const raw=String(q||'').trim(),digits=watchNormCode(raw);let exact=(items||[]).find(x=>String(x.f14||'').trim()===raw);if(exact)return exact;if(digits){exact=(items||[]).find(x=>{const c=String(x.f12||'').replace(/\D/g,'');return c===digits||String(parseInt(c||'0',10))===String(parseInt(digits||'0',10))});if(exact)return exact}return raw?(items||[]).find(x=>String(x.f14||'').includes(raw)||raw.includes(String(x.f14||'')))||null:null}
function watchNormalize(x,m){if(!x)return null;return {code:String(x.f12||''),name:String(x.f14||''),market:m,price:n(x.f2),pct:n(x.f3),amount:bn(x.f6),turn:n(x.f8),vr:n(x.f10),flow:n(x.f62),flowPct:n(x.f184),score:scoreStock(x),ts:Date.now()}}
function quoteUrl(secid){return `${EM_QUOTE}?secid=${encodeURIComponent(secid)}&fltt=2&invt=2&ut=${EM_UT}&fields=f43,f47,f48,f50,f57,f58,f62,f168,f170,f184`}
function directNormalize(x,m){if(!x||!x.f58||!x.f57)return null;const rawAmount=n(x.f48),pct=n(x.f170),turn=n(x.f168),vr=n(x.f50),flow=n(x.f62),flowPct=n(x.f184),price=n(x.f43);const pseudo={f3:pct,f6:rawAmount,f8:turn,f10:vr,f184:flowPct};return {code:String(x.f57),name:String(x.f58),market:m,price,pct,amount:bn(rawAmount),turn,vr,flow,flowPct,score:scoreStock(pseudo),ts:Date.now()}}
function codeCandidates(d){const a=[];if(d.length<=5)a.push(['HK',`116.${d.padStart(5,'0')}`]);if(d.length===6){if(/^(5|6|7|9)/.test(d))a.push(['A',`1.${d}`],['A',`0.${d}`]);else a.push(['A',`0.${d}`],['A',`1.${d}`]);}return a}
async function directQuote(code){const d=watchNormCode(code);if(!d)return null;for(const [m,secid] of codeCandidates(d)){try{const r=await jsonp(quoteUrl(secid),10000);const x=directNormalize(r?.data,m);if(x)return x}catch(e){}}return null}
function watchUniverse(m){return m==='A'?'m:0+t:6,m:0+t:80,m:1+t:2,m:1+t:23':'m:116,m:128'}
async function broadSearch(q,m){try{const url=`${EM}?pn=1&pz=${m==='HK'?10000:6000}&po=1&np=1&fltt=2&invt=2&fid=f6&fs=${encodeURIComponent(watchUniverse(m))}&fields=f12,f14,f2,f3,f5,f6,f8,f10,f62,f184`;const r=await jsonp(url,15000),x=watchMatch(r?.data?.diff,q);return x?watchNormalize(x,m):null}catch(e){return null}}
async function resolveWatchQuote(q){const raw=String(q||'').trim(),digits=watchNormCode(raw);if(digits){const x=await directQuote(digits);if(x)return x}const local=[...state.A.stocks.map(x=>({...x,market:'A'})),...state.HK.stocks.map(x=>({...x,market:'HK'}))];let hit=local.find(x=>x.name===raw||String(x.code)===raw||(digits&&String(parseInt(String(x.code).replace(/\D/g,'')||'0',10))===String(parseInt(digits||'0',10))));if(hit)return {...hit,market:hit.market||'A',ts:Date.now()};for(const m of ['A','HK']){const x=await broadSearch(raw,m);if(x)return x}return null}
function migrateWatchKey(oldKey,newCode){let w=getWatch().map(String);const i=w.indexOf(String(oldKey));if(i>=0)w[i]=String(newCode);w=[...new Set(w)].slice(0,50);localStorage.setItem(WATCH_KEY,JSON.stringify(w))}
async function refreshOneWatch(key){const detail=getWatchDetail();const cached=detail[String(key)];if(cached&&Date.now()-n(cached.ts)<30000)return cached;let x=await directQuote(key);if(!x)x=await resolveWatchQuote(key);if(x){detail[String(x.code)]=x;if(String(key)!==String(x.code))delete detail[String(key)];saveWatchDetail(detail);migrateWatchKey(key,x.code);const bucket=state[x.market]?.stocks;if(bucket){const i=bucket.findIndex(s=>String(s.code)===String(x.code));if(i>=0)bucket[i]={...bucket[i],...x};else bucket.push(x)}return x}return null}
async function refreshWatchQuotes(){const keys=getWatch().slice(0,50);if(!keys.length){renderWatch();return}document.getElementById('watchList').innerHTML='<div class="empty">正在更新自选行情…</div>';for(const k of keys)await refreshOneWatch(k);renderWatch()}
addWatch=async function(){const input=document.getElementById('watchInput'),v=input.value.trim();if(!v)return;const box=document.getElementById('watchList');box.innerHTML='<div class="empty">正在直连查询股票行情…</div>';const x=await resolveWatchQuote(v);if(!x){const d=watchNormCode(v),hint=d?`代码 ${d} 直查失败（不是股票池未覆盖）`:`没有匹配到“${v}”`;box.innerHTML=`<div class="empty">${hint}。请点“刷新雷达”后再试；若仍失败会显示为接口连接问题。</div>`;return}let w=getWatch().map(String);if(!w.includes(String(x.code)))w=[String(x.code),...w].slice(0,50);localStorage.setItem(WATCH_KEY,JSON.stringify(w));const detail=getWatchDetail();detail[String(x.code)]=x;saveWatchDetail(detail);const bucket=state[x.market].stocks,i=bucket.findIndex(s=>String(s.code)===String(x.code));if(i>=0)bucket[i]={...bucket[i],...x};else bucket.push(x);input.value='';renderWatch()}
renderWatch=function(){const w=getWatch().map(String),detail=getWatchDetail(),all=[...state.A.stocks.map(x=>({...x,market:'A'})),...state.HK.stocks.map(x=>({...x,market:'HK'}))],map=new Map(all.map(x=>[String(x.code),x]));document.getElementById('watchList').innerHTML=w.map(code=>{const x=map.get(code)||detail[code];if(!x)return `<div class="row"><div class="rank">★</div><div><div class="name">${code}</div><div class="meta">单股行情接口暂未返回数据 · 点“刷新雷达”重试</div></div><div class="right"><button class="scorepill mid" onclick="event.stopPropagation();toggleWatch('${code}')">移除</button></div></div>`;return `<div class="row"><div class="rank">★</div><div><div class="name">${x.name} <span style="font-size:10px;color:#6f829f">${x.code}${x.market==='HK'?' · HK':''}</span></div><div class="meta">资金分 ${Math.round(n(x.score))} · 成交 ${fmtAmt(n(x.amount))} · 换手 ${n(x.turn).toFixed(1)}% · 量比 ${n(x.vr).toFixed(1)}</div></div><div class="right"><div class="pct ${clsPct(n(x.pct))}">${n(x.pct)>=0?'+':''}${n(x.pct).toFixed(2)}%</div><button class="scorepill" onclick="event.stopPropagation();toggleWatch('${code}')">已收藏</button></div></div>`}).join('')||'<div class="empty">还没有自选。支持 A股/港股名称或代码。</div>'}
const _oldRefreshAll=refreshAll;refreshAll=async function(){await _oldRefreshAll();await refreshWatchQuotes()}
setTimeout(()=>{refreshWatchQuotes().catch(()=>{})},900);
