// V2.3 watchlist quote resolver: supports A/HK codes and names outside the radar Top50.
const WATCH_DETAIL_KEY='fundRadarWatchDetailV23';
function getWatchDetail(){try{return JSON.parse(localStorage.getItem(WATCH_DETAIL_KEY)||'{}')}catch(e){return {}}}
function saveWatchDetail(d){try{localStorage.setItem(WATCH_DETAIL_KEY,JSON.stringify(d))}catch(e){}}
function watchNormCode(v){return String(v||'').trim().toUpperCase().replace(/\.HK$/,'').replace(/[^0-9]/g,'')}
function watchMatch(items,q){const raw=String(q||'').trim(),digits=watchNormCode(raw);let exact=(items||[]).find(x=>String(x.f14||'').trim()===raw);if(exact)return exact;if(digits){exact=(items||[]).find(x=>{const c=String(x.f12||'').replace(/\D/g,'');return c===digits||String(parseInt(c||'0',10))===String(parseInt(digits||'0',10))});if(exact)return exact}return (items||[]).find(x=>String(x.f14||'').includes(raw)||raw.includes(String(x.f14||'')))||null}
function watchNormalize(x,m){if(!x)return null;return {code:String(x.f12||''),name:String(x.f14||''),market:m,price:n(x.f2),pct:n(x.f3),amount:bn(x.f6),turn:n(x.f8),vr:n(x.f10),flow:n(x.f62),flowPct:n(x.f184),score:scoreStock(x),ts:Date.now()}}
function watchUniverse(m){return m==='A'?'m:0+t:6,m:0+t:80,m:1+t:2,m:1+t:23':'m:116+t:1,m:116+t:2,m:116+t:3,m:116+t:4,m:128+t:1,m:128+t:2,m:128+t:3,m:128+t:4'}
async function resolveWatchQuote(q){const local=[...state.A.stocks.map(x=>({...x,market:'A'})),...state.HK.stocks.map(x=>({...x,market:'HK'}))];const raw=String(q||'').trim(),digits=watchNormCode(raw);let hit=local.find(x=>x.name===raw||String(x.code)===raw||(digits&&String(parseInt(String(x.code).replace(/\D/g,'')||'0',10))===String(parseInt(digits||'0',10))));if(hit)return {...hit,market:hit.market||'A',ts:Date.now()};for(const m of ['HK','A']){try{const url=`${EM}?pn=1&pz=${m==='HK'?6000:5000}&po=1&np=1&fltt=2&invt=2&fid=f6&fs=${encodeURIComponent(watchUniverse(m))}&fields=f12,f14,f2,f3,f5,f6,f8,f10,f62,f184`;const r=await jsonp(url,12000);const x=watchMatch(r?.data?.diff,raw);if(x)return watchNormalize(x,m)}catch(e){}}
return null}
function migrateWatchKey(oldKey,newCode){let w=getWatch().map(String);const i=w.indexOf(String(oldKey));if(i>=0)w[i]=String(newCode);w=[...new Set(w)].slice(0,50);localStorage.setItem(WATCH_KEY,JSON.stringify(w))}
async function refreshOneWatch(key){const detail=getWatchDetail();const cached=detail[String(key)];if(cached&&Date.now()-n(cached.ts)<45000)return cached;const x=await resolveWatchQuote(key);if(x){detail[String(x.code)]=x;if(String(key)!==String(x.code))delete detail[String(key)];saveWatchDetail(detail);migrateWatchKey(key,x.code);const bucket=state[x.market]?.stocks;if(bucket&&!bucket.some(s=>String(s.code)===String(x.code)))bucket.push(x);return x}return null}
async function refreshWatchQuotes(){const keys=getWatch().slice(0,50);if(!keys.length){renderWatch();return}document.getElementById('watchList').innerHTML='<div class="empty">正在更新自选行情…</div>';for(const k of keys)await refreshOneWatch(k);renderWatch()}
addWatch=async function(){const input=document.getElementById('watchInput'),v=input.value.trim();if(!v)return;document.getElementById('watchList').innerHTML='<div class="empty">正在搜索 A股 + 港股…</div>';const x=await resolveWatchQuote(v);if(!x){document.getElementById('watchList').innerHTML=`<div class="empty">没有找到“${v}”。可输入名称或代码，例如：耐世特 / 01316。</div>`;return}let w=getWatch().map(String);if(!w.includes(String(x.code)))w=[String(x.code),...w].slice(0,50);localStorage.setItem(WATCH_KEY,JSON.stringify(w));const d=getWatchDetail();d[String(x.code)]=x;saveWatchDetail(d);if(!state[x.market].stocks.some(s=>String(s.code)===String(x.code)))state[x.market].stocks.push(x);input.value='';renderWatch()}
renderWatch=function(){const w=getWatch().map(String),detail=getWatchDetail(),all=[...state.A.stocks.map(x=>({...x,market:'A'})),...state.HK.stocks.map(x=>({...x,market:'HK'}))],map=new Map(all.map(x=>[String(x.code),x]));document.getElementById('watchList').innerHTML=w.map(code=>{const x=map.get(code)||detail[code];if(!x)return `<div class="row"><div class="rank">★</div><div><div class="name">${code}</div><div class="meta">暂时取不到行情，可点“刷新雷达”重试</div></div><div class="right"><button class="scorepill mid" onclick="event.stopPropagation();toggleWatch('${code}')">移除</button></div></div>`;return `<div class="row"><div class="rank">★</div><div><div class="name">${x.name} <span style="font-size:10px;color:#6f829f">${x.code}${x.market==='HK'?' · HK':''}</span></div><div class="meta">资金分 ${Math.round(n(x.score))} · 成交 ${fmtAmt(n(x.amount))} · 换手 ${n(x.turn).toFixed(1)}% · 量比 ${n(x.vr).toFixed(1)}</div></div><div class="right"><div class="pct ${clsPct(n(x.pct))}">${n(x.pct)>=0?'+':''}${n(x.pct).toFixed(2)}%</div><button class="scorepill" onclick="event.stopPropagation();toggleWatch('${code}')">已收藏</button></div></div>`}).join('')||'<div class="empty">还没有自选。现在支持 A股/港股名称或代码搜索。</div>'}
const _oldRefreshAll=refreshAll;refreshAll=async function(){await _oldRefreshAll();await refreshWatchQuotes()}
setTimeout(()=>{refreshWatchQuotes().catch(()=>{})},900);