const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict'),path=require('node:path');
const elements=new Map(),values=new Map();function element(){return {classList:{toggle(){},add(){},remove(){}},appendChild(){},insertBefore(){},remove(){},innerHTML:'',textContent:''};}
const document={hidden:true,createElement:element,getElementById(id){if(!elements.has(id))elements.set(id,element());return elements.get(id);},querySelector(){return element();},head:element(),body:element(),addEventListener(){}};
let mode='normal';const stamp=Date.parse('2026-09-08T08:15:00Z')/1000;
const ctx={document,window:{__REVIEW_TEST__:{}},localStorage:{getItem:k=>values.get(k)||null,setItem:(k,v)=>values.set(k,v)},EM:'https://push2.eastmoney.com/api/qt/clist/get',URLSearchParams,Date,Promise,Math,Number,String,Object,Array,Set,setTimeout,clearTimeout,setInterval(){},currentTab:'radar',market:'A',showTab(){},switchMarket(){},cap:s=>s[0].toUpperCase()+s.slice(1)};
document.body.appendChild=s=>{const u=new URL(s.src),cb=u.searchParams.get('cb');queueMicrotask(()=>{if(mode==='offline')return s.onerror();const filter=u.searchParams.get('fs'),pn=+u.searchParams.get('pn')||1;let total=205,diff=[];
if(u.pathname.includes('ulist')){diff=(u.searchParams.get('secids')||'').split(',').map(id=>({f12:id.split('.')[1],f14:id,f3:1,f124:stamp}));total=diff.length;}
else if(filter==='m:124'||filter==='m:90+t:2'){total=10;diff=Array.from({length:10},(_,i)=>({f12:filter==='m:124'?'H'+i:'BK'+i,f13:filter==='m:124'?124:90,f14:'sector'+i,f3:i-5,f6:1e9,f62:(i-5)*1e8,f124:stamp}));}
else {const start=mode==='repeat'?0:(pn-1)*100;diff=Array.from({length:Math.min(100,205-start)},(_,i)=>({f12:String(start+i),f13:0,f14:'stock'+i,f3:i%5?-1:2,f6:1e8,f62:i%2?'-':0,f124:stamp}));}
ctx.window[cb]({rc:0,data:{total,diff}});});};
vm.runInNewContext(fs.readFileSync(path.join(__dirname,'../fund-radar/review-addon.js'),'utf8'),ctx);const a=ctx.window.__REVIEW_TEST__.api;
(async()=>{assert.equal(a.num('-'),null);assert.equal(a.num(null),null);assert.equal(a.num(0),0);assert.equal(a.num(-20),-20);assert.equal(a.emotion({up:80,count:100},true).label,'高潮');assert.equal(a.emotion({up:20,count:100},true).label,'退潮');assert.equal(a.emotion({up:50,count:100},true).label,'分歧');assert.equal(a.emotion({up:80,count:100},false).label,'数据不足');assert.equal(a.clock(Date.parse('2026-09-08T16:00:00Z')).date,'2026-09-09');let r=await a.all('stocks');assert.equal(r.rows.length,205);assert.equal(r.complete,true);mode='repeat';r=await a.all('stocks');assert.equal(r.rows.length,100);assert.equal(r.complete,false);mode='normal';for(const m of ['A','HK']){r=await a.collect(m);assert.equal(r.market,m);assert.equal(r.date,'2026-09-08');assert.equal(r.breadth.count,205);assert.equal(r.sectors.length,10);assert.equal(r.closed,true);assert.equal(a.latest(m).date,r.date);a.memory[m]=r;ctx.currentTab='review';ctx.market=m;a.draw(m);assert(document.getElementById('reviewBody').innerHTML.includes('收盘后复盘'));assert(document.getElementById('reviewBody').innerHTML.includes('-5.00亿'));}mode='offline';await a.refresh('HK');assert(document.getElementById('reviewStatus').textContent.includes('保留上次快照'));assert(document.getElementById('reviewBody').innerHTML.includes('本机历史快照'));console.log('PASS review logic: A/HK, pagination, duplicate pages, missing/negative values, sentiment, timezone, close status, local snapshots, offline fallback and rendered conclusions.');})().catch(e=>{console.error(e);process.exitCode=1;});
