const words=[['晨','chén','早晨','早晨，阳光照进窗户。'],['绒','róng','绒球','帽子上有一个小绒球。'],['静','jìng','安静','图书馆里十分安静。'],['趣','qù','有趣','这个故事真有趣。'],['察','chá','观察','我们仔细观察树叶。'],['旅','lǚ','旅行','假期里，我们去旅行。'],['准','zhǔn','准备','我准备好明天的课本。'],['摇','yáo','摇晃','树枝在风中轻轻摇晃。'],['颗','kē','一颗','天空中有一颗星星。'],['棵','kē','一棵','院子里有一棵桂花树。'],['城','chéng','城市','南京是一座美丽的城市。'],['诚','chéng','诚实','我们要做诚实的孩子。'],['飘','piāo','飘扬','红旗在风中飘扬。'],['漂','piào','漂亮','这朵花真漂亮。'],['净','jìng','干净','我把桌子擦得很干净。'],['径','jìng','小径','小径通向树林深处。'],['惜','xī','珍惜','我们要珍惜时间。'],['勇','yǒng','勇敢','她勇敢地说出了想法。'],['晒','shài','晒太阳','小猫在窗边晒太阳。'],['滴','dī','水滴','水滴落在叶子上。'],['奏','zòu','演奏','姐姐正在演奏乐曲。'],['柔','róu','轻柔','妈妈的声音很轻柔。'],['舒','shū','舒服','微风吹来，真舒服。'],['膀','bǎng','翅膀','小鸟展开了翅膀。']];
const qs=[];function add(type,q,opts,ans,why,extra={}){qs.push({id:'q'+qs.length,type,q,opts,ans,why,...extra})}
words.forEach(w=>{const opts=[w[1],...words.filter(x=>x[1]!==w[1]).map(x=>x[1]).filter((x,i,a)=>a.indexOf(x)===i).slice(0,3)];add('字',`“${w[0]}”在“${w[2]}”中读什么？`,opts,w[1],`“${w[2]}”中的“${w[0]}”读 ${w[1]}。${w[3]}`)});
[
['一（　）大树','棵|颗|课','棵','“棵”常用于植物，如一棵树、一棵草。'],['一（　）星星','颗|棵|课','颗','“颗”常用于小而圆的东西，如星星、珠子。'],['教室里十分（　），大家都在读书。','安静|安定|安全','安静','这里强调没有吵闹声，用“安静”。'],['“仔细”的近义词是？','认真|马虎|着急','认真','“仔细”和“认真”都有用心、不马虎的意思。'],['“粗心”的反义词是？','细心|开心|伤心','细心','“细心”和“粗心”意思相反。'],['选出书写正确的词语。','旅游|旅由|族游','旅游','“旅游”的“旅”右边不要写成“族”。'],['把花的颜色写具体：金（　）的菊花。','黄|红|绿','黄','“金黄”是一种像金子一样的黄色。'],['风一吹，红旗高高（　）。','飘扬|漂扬|飘杨','飘扬','“飘扬”指随风摆动，用“飘”。'],['“秋高气爽”通常描写哪个季节？','秋天|夏天|冬天','秋天','“秋高气爽”形容秋天天空晴朗，天气凉爽。'],['补充词语：大吃一（　）。','惊|京|经','惊','“大吃一惊”形容非常惊讶。'],['“五彩缤纷”形容什么？','颜色多而美丽|声音很响|速度很快','颜色多而美丽','“五彩缤纷”形容色彩繁多，非常好看。'],['选一个合适的动作：小鱼在水里（　）。','游来游去|飞来飞去|跑来跑去','游来游去','鱼用鳍和尾巴在水中游动。'],['选择正确的词语：我（　）了他的建议。','接受|接收|接手','接受','对于建议、意见，可以说“接受”。'],['“陆续走进教室”是什么意思？','一个接一个地走进来|同时走进来|一直站着不动','一个接一个地走进来','“陆续”表示先后相继，不是同时发生。'],['一（　）秋风吹过。','阵|座|本','阵','“阵”可以用于一段时间内发生的风、雨、掌声等。'],['补充词语：一本正（　）。','经|惊|京','经','“一本正经”形容态度庄重、严肃。']
].forEach(x=>add('词',x[0],x[1].split('|'),x[2],x[3]));
[
['小鸟|在枝头|快乐地|唱歌。','谁在哪里，怎样地做什么：小鸟在枝头快乐地唱歌。'],['我|把落叶|夹进了|书里。','“把”字句说明怎样处理事物：把落叶夹进书里。'],['弯弯的月亮|像|一只小船。','把月亮比作小船，写出了它弯弯的样子。'],['因为下雨了，|所以|我们带上了雨伞。','“因为”说原因，“所以”说结果。'],['妹妹|捧着一本书，|读得|津津有味。','先说谁做什么，再说明读书时的样子。'],['一阵秋风|吹来，|树叶|纷纷落下。','先写风吹来，再写树叶落下，顺序清楚。'],['只要认真练习，|就能|一点点进步。','“只要……就……”说明条件与结果。'],['小明|先洗手，|再吃饭。','“先……再……”表示动作的先后顺序。']
].forEach(x=>add('句','点词块，把句子排通顺。',[],x[0].split('|').join(''),x[1],{tiles:x[0].split('|')}));
[
['哪一句是比喻句？','落叶像一只只蝴蝶。|落叶从树上落下来。|树上有许多叶子。','落叶像一只只蝴蝶。','把落叶比作蝴蝶，让我们想到落叶飞舞的样子。'],['哪一句表达最完整？','小猫在窗边晒太阳。|小猫在。|在窗边的。','小猫在窗边晒太阳。','完整地说清了谁、在哪里、做什么。'],['“你带铅笔了吗”结尾应该用什么？','？|。|！','？','这句话在提出问题，要用问号。'],['哪句话没有语病？','花园里开着五颜六色的花。|花园里开着五颜六色的红花。|花园里开着一朵许多花。','花园里开着五颜六色的花。','“五颜六色”不能只说红色；“一朵”和“许多”也互相矛盾。']
].forEach(x=>add('句',x[0],x[1].split('|'),x[2],x[3]));
const passages=[
['落叶书签','星期六，小雨和爸爸来到公园。银杏叶像一把把小扇子，铺在路上。小雨捡起一片完整的黄叶，轻轻夹进书里。爸爸问：“这是做什么？”小雨笑着说：“我要把秋天留在书里。”',[
['小雨捡起的是什么？','一片完整的黄叶|一朵红花|一根树枝','一片完整的黄叶','原文写着“小雨捡起一片完整的黄叶”。'],['银杏叶被比作什么？','小扇子|小雨伞|小星星','小扇子','“银杏叶像一把把小扇子”写出了叶子的形状。'],['“把秋天留在书里”是指什么？','用秋天的落叶做书签|把公园搬进书里|让秋天不再结束','用秋天的落叶做书签','联系“轻轻夹进书里”，可以知道她想用落叶留下秋天的记忆。']]],
['窗边的小苗','小禾在窗边种了一盆豆苗。起初，她每天都浇很多水，叶子却渐渐发黄。妈妈摸了摸湿湿的泥土，说：“水太多，根也会不舒服。”小禾减少了浇水的次数，又让豆苗晒到温暖的阳光。过了几天，新叶子冒出来了。',[
['叶子发黄的原因是什么？','浇水太多|没有花盆|没有种子','浇水太多','妈妈说“水太多”，这提示了发黄的原因。'],['后来小禾怎么做？','少浇些水，让豆苗晒太阳|每天浇更多水|把新叶子摘掉','少浇些水，让豆苗晒太阳','原文写到她“减少了浇水的次数”，又让豆苗晒到阳光。'],['哪个题目也适合这篇短文？','学着照顾豆苗|会飞的种子|窗外的大雨','学着照顾豆苗','整篇讲的是小禾发现问题、调整方法、照顾豆苗的过程。']]],
['雨中的伞','放学时，雨突然下大了。小安撑开雨伞，看见同桌站在门口，望着雨发愁。“一起走吧！”小安把伞往同桌那边移了移。到了路口，同桌发现小安的一边肩膀湿了。他赶紧把伞推回中间，两个人靠近了一些。',[
['同桌起初为什么发愁？','下着大雨，自己没有撑伞|忘了带课本|找不到教室','下着大雨，自己没有撑伞','结合下雨、站在门口和小安邀请共伞，可以推知原因。'],['小安的肩膀为什么湿了？','他把伞往同桌那边移了|他跳进了水坑|他在洗衣服','他把伞往同桌那边移了','伞向同桌那边移动，小安的一边肩膀就没有完全被遮住。'],['两个人的举动表现了什么？','互相关心|互相生气|互相比赛','互相关心','小安让出伞，同桌又把伞推回中间，都在为对方着想。']]],
['晨读的小办法','乐乐读故事时，总想一下子读得很快，结果常常漏字。老师建议她用手指轻轻点着字，先读准确，再读流利。第二天，乐乐放慢速度，一句一句地读。读完后，她发现自己漏掉的字少了，故事的意思也更明白了。',[
['乐乐最初遇到了什么问题？','读得太快，常常漏字|不认识所有的字|找不到故事书','读得太快，常常漏字','第一句话直接告诉我们她的问题。'],['老师建议先做到什么？','读准确|读得最快|背下全篇','读准确','老师说“先读准确，再读流利”。'],['短文告诉我们什么？','方法合适比一味求快更有帮助|读书越快越好|读书不用理解','方法合适比一味求快更有帮助','放慢速度后，她漏字少了，也更理解故事，说明方法起了作用。']]]];
passages.forEach(p=>p[2].forEach(x=>add('读',x[0],x[1].split('|'),x[2],x[3],{title:p[0],passage:p[1]})));
let saved={stars:0,wrong:[],done:0};try{saved={...saved,...JSON.parse(localStorage.getItem('hanziForest')||'{}')}}catch{}let queue=[],index=0,score=0,locked=false,selected=[],flashIndex=0,flipped=false,mode='';const app=document.querySelector('#app');const shuffle=a=>[...a].sort(()=>Math.random()-.5);function persist(){try{localStorage.setItem('hanziForest',JSON.stringify(saved))}catch{}}function home(){stopReading();app.innerHTML=`<div class="welcome"><div><span class="eyebrow">三年级上 · 基础练习 · 音频版</span><h1>今天，发现汉字的乐趣</h1><p>翻一张卡，闯一小关。每天进步一点点。</p></div><div class="stars">我的星星<strong>★ ${saved.stars}</strong></div></div><section class="feature"><div><span class="badge">今日小冒险 · 6 道题</span><h2>准备好出发了吗？</h2><p>认字、组词、读句子，一起练一练。</p></div><button class="primary" onclick="start('综合')">开始闯关 →</button></section><div class="section-head"><h2>选择你的练习乐园</h2><span class="hint">不限时，慢慢想</span></div><div class="grid">${[['字','识字翻翻卡','翻卡认字 · 拼音与例句'],['词','词语小达人','选字组词 · 近反义词'],['句','句子拼拼乐','排列词块 · 读通句子'],['读','阅读寻宝记','读小故事 · 找答案']].map(x=>`<button class="game" onclick="${x[0]==='字'?'flash(0)':`start('${x[0]}')`}"><span class="glyph">${x[0]}</span><span class="go">↗</span><b>${x[1]}</b><p>${x[2]}</p></button>`).join('')}</div><div class="bottom"><button class="quiet" data-read="你好，欢迎来到字趣森林。">♪ 测试声音</button><button class="quiet" onclick="review()">再练一练 · ${saved.wrong.length} 道错题</button><span class="hint">已完成 ${saved.done} 关<br>进度仅保存在这台设备</span></div>`}
function start(t){mode=t;index=0;score=0;if(t==='错题')queue=shuffle(qs.filter(q=>saved.wrong.includes(q.id))).slice(0,6);else if(t==='读'){const p=passages[Math.floor(Math.random()*passages.length)];queue=qs.filter(q=>q.title===p[0])}else if(t==='综合')queue=shuffle([...shuffle(qs.filter(q=>q.type==='字')).slice(0,2),...shuffle(qs.filter(q=>q.type==='词')).slice(0,2),...shuffle(qs.filter(q=>q.type==='句')).slice(0,2)]);else queue=shuffle(qs.filter(q=>q.type===t)).slice(0,6);if(!queue.length){review();return}renderQ()}
function renderQ(){stopReading();locked=false;selected=[];const q=queue[index];app.innerHTML=`<div class="topline"><button class="quiet" onclick="home()">‹ 返回乐园</button><b>${mode==='综合'?'今日小冒险':mode==='错题'?'再练一练':{'字':'识字挑战','词':'词语小达人','句':'句子拼拼乐','读':'阅读寻宝记'}[mode]}</b><span>${index+1} / ${queue.length}</span></div><div class="bar"><span style="width:${index/queue.length*100}%"></span></div><section class="panel">${q.passage?`<div class="passage"><b>${q.title}</b><button class="read-button" onclick="readAloud(queue[index].passage)">朗读全文</button><div class="passage-lines">${(q.passage.match(/[^。！？]+[。！？]?[”’]?/g)||[q.passage]).map(line=>`<button class="read-line" data-read="${line}">${line}<span aria-hidden="true"> ♪</span></button>`).join('')}</div></div>`:''}<span class="eyebrow">${q.tiles?'词块排序':q.type==='读'?'小提示：回到原文找线索':'选出你认为正确的答案'}</span><h2 class="prompt">${q.q}</h2><button class="read-button" onclick="readAloud(queue[index].q)">听题目</button><div id="play"></div><div id="feedback" aria-live="polite"></div></section>`;if(q.tiles){q.pool=shuffle(q.tiles);renderTiles()}else document.querySelector('#play').innerHTML=`<div class="choices">${shuffle(q.opts).map(o=>`<div class="choice-wrap"><button class="choice" data-answer="${o}">${o}</button>${q.type!=='字'?`<button class="read-option" data-read="${o}" aria-label="朗读选项：${o}">♪ 听</button>`:''}</div>`).join('')}</div>`;document.querySelectorAll('[data-answer]').forEach(b=>b.onclick=()=>answer(b.dataset.answer))}
function renderTiles(){const q=queue[index];document.querySelector('#play').innerHTML=`<div class="sentence" aria-label="已排列的句子">${selected.length?selected.map((n,i)=>`<button class="tile" onclick="removeTile(${i})" ${locked?'disabled':''}>${q.pool[n]}</button>`).join(''):'<span class="hint">依次点击下面的词块</span>'}</div><div class="tiles">${q.pool.map((w,n)=>`<button class="tile" onclick="pickTile(${n})" ${selected.includes(n)||locked?'disabled':''}>${w}</button>`).join('')}</div><button class="read-button" onclick="readTiles()" ${selected.length?'':'disabled'}>听我拼的句子</button><div class="actions"><button class="quiet" onclick="selected=[];renderTiles()" ${locked?'disabled':''}>重新排列</button><button class="primary" onclick="answer(selected.map(n=>queue[index].pool[n]).join(''))" ${selected.length!==q.pool.length||locked?'disabled':''}>排好啦</button></div>`}function pickTile(n){if(!locked&&!selected.includes(n)){selected.push(n);renderTiles()}}function removeTile(i){if(!locked){selected.splice(i,1);renderTiles()}}
function answer(v){if(locked)return;locked=true;const q=queue[index],ok=v===q.ans;if(ok){score++;saved.stars++;saved.wrong=saved.wrong.filter(id=>id!==q.id)}else if(!saved.wrong.includes(q.id))saved.wrong.push(q.id);persist();if(q.tiles)renderTiles();document.querySelectorAll('[data-answer]').forEach(b=>{b.disabled=true;if(b.dataset.answer===q.ans)b.classList.add('good');else if(b.dataset.answer===v)b.classList.add('bad')});document.querySelector('#feedback').innerHTML=`<div class="feedback"><b>${ok?'★ 答对啦，获得一颗星！':'再想一想，你正在进步。'}</b>${!ok?`<div>正确答案：${q.ans}</div>`:''}<div>${q.why}</div><button class="read-button" onclick="readAloud(queue[index].ans+'。'+queue[index].why)">听答案和讲解</button><button class="primary" onclick="next()">${index===queue.length-1?'看看收获':'下一题 →'}</button></div>`}
function next(){stopReading();index++;if(index<queue.length)renderQ();else{saved.done++;persist();app.innerHTML=`<section class="panel result"><div class="bigstar">★</div><h1>${score===queue.length?'这一关，全答对啦！':'又完成了一次小冒险！'}</h1><p>答对 ${score} / ${queue.length} 题，收获 ${score} 颗星星。<br>${score===queue.length?'读得仔细，想得认真，真不错。':'不会的题，读懂讲解后再试一次就好。'}</p><div class="actions"><button class="primary" onclick="start(mode)">再玩一关</button><button class="quiet" onclick="home()">返回乐园</button></div>${saved.wrong.length?'<button class="quiet" style="margin-top:20px" onclick="start(\'错题\')">练练错题</button>':''}<p class="hint">让眼睛休息一下，也可以讲给爸爸妈妈听。</p></section>`}}
function flash(n){stopReading();flashIndex=(n+words.length)%words.length;flipped=false;renderFlash()}function renderFlash(){const w=words[flashIndex];app.innerHTML=`<div class="topline"><button class="quiet" onclick="home()">‹ 返回乐园</button><b>识字翻翻卡</b><span>${flashIndex+1} / ${words.length}</span></div><section class="panel"><p class="hint">先试着读一读，再点击卡片看答案。</p><button class="flash" onclick="flipped=!flipped;renderFlash()" aria-label="翻转识字卡"><span class="pinyin">${flipped?w[1]:'想一想，怎么读？'}</span><strong class="hanzi">${w[0]}</strong><span class="example">${flipped?`${w[2]}<br>${w[3]}`:'点我翻面 ↻'}</span></button><div class="actions"><button class="quiet" onclick="flash(flashIndex-1)">上一张</button><button class="quiet" onclick="readAloud(words[flashIndex][2])">听字词</button><button class="quiet" onclick="speak()">听例句</button><button class="primary" onclick="flash(flashIndex+1)">下一张</button></div><p id="voiceStatus" class="hint" aria-live="polite"></p><button class="quiet" style="width:100%;margin-top:12px" onclick="start('字')">我来挑战认字 →</button></section>`}
function speak(){readAloud(words[flashIndex][2]+'。'+words[flashIndex][3])}
let readingId=0,readingTimer=null,audioQueue=[],audioIndex=0,activeReadSource=null;
function voiceStatus(message){document.querySelector('#readerStatus').textContent=message}
function stopReading(){readingId++;clearTimeout(readingTimer);const player=document.querySelector('#voiceAudio');if(player){player.pause();player.removeAttribute('src');player.load()}audioQueue=[];activeReadSource?.classList.remove('is-reading');activeReadSource=null;const bar=document.querySelector('#reader');if(bar)bar.hidden=true}
function readAloud(text,source){playRecordings([text],source)}
function readTiles(){playRecordings(selected.map(n=>queue[index].pool[n]))}
function playRecordings(texts,source){
 stopReading();if(!texts.length)return;
 document.querySelector('#reader').hidden=false;
 const map=window.CHINESE_AUDIO||{};audioQueue=texts.map(text=>map[text]);
 if(audioQueue.some(url=>!url)){voiceStatus('这段语音尚未加载，请刷新页面后重试。');return}
 activeReadSource=source;source?.classList.add('is-reading');audioIndex=0;const id=readingId;
 const player=document.querySelector('#voiceAudio');
 function playNext(){if(id!==readingId)return;clearTimeout(readingTimer);player.src=audioQueue[audioIndex];player.playbackRate=Number(document.querySelector('#readSpeed').value);voiceStatus('正在加载语音…');
 readingTimer=setTimeout(()=>{if(id===readingId)voiceStatus('加载较慢，可点下方播放键重试。')},10000);
 const result=player.play();if(result?.catch)result.catch(()=>{if(id!==readingId)return;clearTimeout(readingTimer);voiceStatus('请点下方 ▶ 播放键开始朗读。')})}
 player.onplaying=()=>{if(id!==readingId)return;clearTimeout(readingTimer);voiceStatus('正在朗读 '+(audioIndex+1)+' / '+audioQueue.length)};
 player.onended=()=>{if(id!==readingId)return;clearTimeout(readingTimer);if(audioIndex+1<audioQueue.length){audioIndex++;playNext()}else{voiceStatus('读完啦，点播放键可以再听一遍。');activeReadSource?.classList.remove('is-reading')}};
 player.onerror=()=>{if(id!==readingId)return;clearTimeout(readingTimer);voiceStatus('音频加载失败，请检查网络后再点朗读。')};
 playNext();
}
document.addEventListener('click',e=>{const button=e.target.closest('[data-read]');if(button)readAloud(button.dataset.read,button)});
document.addEventListener('visibilitychange',()=>{if(document.hidden)stopReading()});

function review(){stopReading();const items=qs.filter(q=>saved.wrong.includes(q.id));app.innerHTML=`<div class="topline"><button class="quiet" onclick="home()">‹ 返回乐园</button><h2>再练一练</h2><span>${items.length} 题</span></div>${items.length?`<p>读懂原因，再挑战一次。答对后会自动移出错题。</p><button class="primary" style="margin-bottom:22px" onclick="start('错题')">开始复习</button><div class="review-list">${items.map(q=>`<div class="review-item"><b>${q.title?q.title+' · ':''}${q.q}</b><p>答案：${q.ans}</p><p class="hint">${q.why}</p><button class="read-button" data-read="${q.ans}。${q.why}">听答案和讲解</button></div>`).join('')}</div>`:'<section class="panel result"><h2>这里还没有错题</h2><p>去选一个小游戏，开始今天的练习吧。</p><button class="primary" onclick="home()">去乐园</button></section>'}`}
document.querySelector('#readSpeed').onchange=()=>{document.querySelector('#voiceAudio').playbackRate=Number(document.querySelector('#readSpeed').value)};document.querySelector('#brand').onclick=e=>{e.preventDefault();home()};document.querySelector('#parent').onclick=()=>document.querySelector('#info').showModal();document.querySelector('#closeInfo').onclick=()=>document.querySelector('#info').close();home();
